// macrow course content — sourced from IBDP Economics syllabus, Unit 3 (Macroeconomics).
// Each module corresponds to a syllabus sub-topic (3.1 – 3.7). Each module has lessons
// (concept explanation + linked diagram + practice questions). Glossary entries are
// the canonical definitions.

export const COURSE = [
  {
    id: '3.1',
    code: '3.1',
    title: 'Measuring economic activity',
    blurb: 'How we count what an economy produces, and why the headcount is more than a number.',
    outcomes: [
      'Explain the equivalence of income, output and expenditure approaches using the circular flow.',
      'Distinguish nominal from real GDP and GNI, and calculate real values using a price deflator.',
      'Discuss the appropriateness of GDP/GNI for measuring well-being, with reference to alternative indices.',
    ],
    lessons: [
      {
        id: '3.1.1',
        title: 'The circular flow of income',
        minutes: 8,
        body: [
          'The circular flow shows how money, goods and services move between households, firms, the government and the foreign sector.',
          'Injections (investment, government spending, exports) add to the flow; leakages (saving, taxes, imports) drain it. In equilibrium injections equal leakages.',
          'The three approaches to national income — output, income and expenditure — give the same total because every transaction is both a payment and a receipt.',
        ],
        diagram: 'circularFlow',
        keyTerms: ['circular flow', 'injections', 'leakages', 'expenditure approach', 'income approach', 'output approach'],
      },
      {
        id: '3.1.2',
        title: 'GDP, GNI, and the difference between them',
        minutes: 7,
        body: [
          'Gross Domestic Product (GDP) measures the total market value of all final goods and services produced within a country in a period.',
          'Gross National Income (GNI) = GDP + net primary income from abroad (income residents earn overseas minus income foreigners earn domestically).',
          'Both can be reported nominal (at current prices) or real (adjusted for inflation using a price deflator). Real values are what allow comparisons over time.',
        ],
        formula: 'Real GDP = (Nominal GDP / Price deflator) × 100',
        diagram: null,
        keyTerms: ['GDP', 'GNI', 'price deflator', 'net primary income', 'final goods and services'],
      },
      {
        id: '3.1.3',
        title: 'Per capita measures and cross-country comparisons',
        minutes: 6,
        body: [
          'Real GDP per capita = Real GDP / Population. Useful for comparing average living standards.',
          'Purchasing Power Parity (PPP) adjusts for differences in price levels across countries, so a dollar buys the same bundle everywhere.',
          'GDP/GNI per capita at PPP is the standard cross-country welfare comparison, but it still misses inequality, environment, and unpaid work.',
        ],
        diagram: null,
        keyTerms: ['GDP per capita', 'purchasing power parity (PPP)'],
      },
      {
        id: '3.1.4',
        title: 'The business cycle and potential output',
        minutes: 9,
        body: [
          'Real GDP fluctuates around a long-term growth trend. The business cycle has four phases: expansion, peak, contraction (recession), trough.',
          'Potential output (Yf) is the level of real GDP consistent with the natural rate of unemployment. The output gap is the difference between actual and potential output.',
          'Recessionary gap: actual < potential. Inflationary gap: actual > potential (Keynesian view; some schools call this a positive output gap).',
        ],
        diagram: 'businessCycle',
        keyTerms: ['business cycle', 'potential output', 'output gap', 'recession', 'expansion', 'peak', 'trough'],
      },
      {
        id: '3.1.5',
        title: 'Beyond GDP — measuring well-being',
        minutes: 6,
        body: [
          'GDP is a measure of output, not welfare. It ignores income distribution, non-market work, environmental damage, and quality of life.',
          'Alternative indices: OECD Better Life Index (11 dimensions), UN Human Development Index, Happy Planet Index (life expectancy × well-being ÷ ecological footprint).',
          'For exam answers: GDP is useful but limited; complement it with at least one alternative index when evaluating well-being.',
        ],
        diagram: null,
        keyTerms: ['OECD Better Life Index', 'Human Development Index (HDI)', 'Happy Planet Index'],
      },
    ],
  },
  {
    id: '3.2',
    code: '3.2',
    title: 'Aggregate demand and aggregate supply',
    blurb: 'The two curves that frame every macro story: what shifts them, and what happens at the intersection.',
    outcomes: [
      'Construct and interpret AD and AS diagrams, including shifts caused by their determinants.',
      'Compare monetarist/new classical and Keynesian views of aggregate supply in the short run and long run.',
      'Explain short-run and long-run macroeconomic equilibrium, including the concepts of inflationary and deflationary gaps.',
    ],
    lessons: [
      {
        id: '3.2.1',
        title: 'The aggregate demand curve',
        minutes: 8,
        body: [
          'Aggregate demand (AD) is the total quantity of real output demanded at each price level. It slopes downward.',
          'AD = C + I + G + (X − M). The downward slope reflects three effects: real balances, interest rate, and international competitiveness.',
          'Determinants of the components:',
        ],
        bullets: [
          'C: consumer confidence, interest rates, wealth, income taxes, household debt, expected future prices.',
          'I: interest rates, business confidence, technology, business taxes, corporate debt.',
          'G: political and economic priorities.',
          'X − M: income of trading partners, exchange rates, trade policies.',
        ],
        diagram: 'ad',
        keyTerms: ['aggregate demand (AD)', 'real balances effect', 'interest rate effect', 'international competitiveness effect'],
      },
      {
        id: '3.2.2',
        title: 'The short-run aggregate supply (SRAS) curve',
        minutes: 7,
        body: [
          'SRAS slopes upward in the short run: higher prices encourage firms to expand output because nominal wages and some input prices are sticky.',
          'Determinants of SRAS: costs of factors of production, indirect taxes, productivity shocks, supply shocks (e.g. oil price).',
          'A rightward shift of SRAS = favourable supply shock (lower costs or higher productivity). A leftward shift = adverse supply shock (cost-push inflation).',
        ],
        diagram: 'sras',
        keyTerms: ['short-run aggregate supply (SRAS)', 'sticky wages', 'cost-push shock', 'favourable supply shock'],
      },
      {
        id: '3.2.3',
        title: 'Two views of long-run aggregate supply',
        minutes: 10,
        body: [
          'Monetarist / new classical view: LRAS is vertical at the natural rate of unemployment. Markets clear; output returns to potential in the long run regardless of AD.',
          'Keynesian view: AS can slope upward over the long term too, because wages and prices adjust slowly. Persistent deflationary gaps are possible.',
          'Both views accept that the economy can deviate from potential in the short run — they disagree on how quickly (or whether) it returns.',
        ],
        diagram: 'lras',
        keyTerms: ['long-run aggregate supply (LRAS)', 'natural rate of unemployment', 'monetarist', 'new classical', 'Keynesian', 'vertical LRAS'],
      },
      {
        id: '3.2.4',
        title: 'Macroeconomic equilibrium: short run and long run',
        minutes: 10,
        body: [
          'Short-run equilibrium: AD = SRAS at the current price level. This gives actual output Y and price level P.',
          'In the monetarist model, the economy self-corrects: if Y > Yf, nominal wages and prices rise, SRAS shifts left until output returns to potential at a higher price.',
          'In the Keynesian model, this adjustment may be slow or incomplete — leaving persistent deflationary gaps that require active policy.',
        ],
        diagram: 'equilibrium',
        keyTerms: ['short-run equilibrium', 'long-run equilibrium', 'self-correction', 'inflationary gap', 'deflationary gap', 'recessionary gap'],
      },
    ],
  },
  {
    id: '3.3',
    code: '3.3',
    title: 'Macroeconomic objectives',
    blurb: 'What governments want: growth, low unemployment, low inflation, balance — and the trade-offs between them.',
    outcomes: [
      'Measure and explain economic growth, unemployment and inflation, including their causes and consequences.',
      'Discuss the trade-offs between the main macroeconomic objectives.',
      '(HL) Discuss the Phillips curve, including the short-run and long-run relationship between inflation and unemployment.',
    ],
    lessons: [
      {
        id: '3.3.1',
        title: 'Economic growth: short-term and long-term',
        minutes: 8,
        body: [
          'Short-term growth is driven by AD. In the AD/AS model, an outward shift of AD raises real output (and prices) in the short run.',
          'Long-term growth is driven by LRAS — the productive capacity of the economy. It requires more or better factors of production, better technology, improved efficiency, and supportive institutions.',
          'PPC shifts outward with growth in production possibilities. In AD/AS terms, LRAS shifts right.',
        ],
        diagram: 'growth',
        keyTerms: ['economic growth', 'short-term growth', 'long-term growth', 'LRAS shift', 'PPC shift'],
      },
      {
        id: '3.3.2',
        title: 'Unemployment: types, measures, costs',
        minutes: 9,
        body: [
          'Unemployment rate = (unemployed ÷ labour force) × 100. The labour force excludes those not actively seeking work.',
          'Types of unemployment:',
        ],
        bullets: [
          'Cyclical (demand-deficient) — falls in AD, associated with recessionary gaps.',
          'Structural — skills mismatch or geographic mismatch between workers and jobs.',
          'Seasonal — predictable variation across the year (e.g. tourism, agriculture).',
          'Frictional — short-run unemployment while workers transition between jobs.',
        ],
        bodyAfter: [
          'The natural rate of unemployment is the sum of structural, seasonal and frictional unemployment — it persists even at potential output.',
          'Costs: personal (income, health, skills), social (inequality, exclusion), economic (lost output, lower tax revenue).',
        ],
        diagram: 'unemployment',
        keyTerms: ['unemployment rate', 'labour force', 'cyclical unemployment', 'structural unemployment', 'frictional unemployment', 'seasonal unemployment', 'natural rate of unemployment'],
      },
      {
        id: '3.3.3',
        title: 'Inflation: causes, measures, costs',
        minutes: 10,
        body: [
          'Inflation is a sustained rise in the general price level. Measured using the Consumer Price Index (CPI): a weighted basket of goods and services.',
          'Causes:',
        ],
        bullets: [
          'Demand-pull — AD rises faster than AS. Often associated with rapid growth above potential.',
          'Cost-push — SRAS shifts left (e.g. oil shock, wage-price spiral). Output falls, prices rise — stagflation.',
        ],
        bodyAfter: [
          'Costs of high inflation: uncertainty, redistributive effects, damaged export competitiveness, lower saving, inefficient resource allocation, slower growth.',
          'Disinflation is a fall in the inflation rate; deflation is a sustained fall in prices. Deflation raises the real value of debt and can cause a debt-deflation spiral.',
          'CPI limitations: quality change, new products, substitution bias, different spending patterns across households.',
        ],
        diagram: 'inflation',
        keyTerms: ['inflation', 'deflation', 'disinflation', 'CPI', 'demand-pull inflation', 'cost-push inflation', 'stagflation'],
      },
      {
        id: '3.3.4',
        title: '(HL) The Phillips curve',
        minutes: 12,
        body: [
          'The Phillips curve shows the inverse relationship between the rate of inflation and the rate of unemployment.',
          'Short-run Phillips curve (SRPC): downward sloping. Policymakers face a trade-off — accept higher inflation to lower unemployment (or vice versa).',
          'Long-run Phillips curve (LRPC): vertical at the natural rate of unemployment. In the long run, attempts to push unemployment below the natural rate only produce accelerating inflation.',
          'Expectations-augmented view: the SRPC shifts when expected inflation changes. The 1970s stagflation episode (high inflation + high unemployment) is the standard example.',
        ],
        diagram: 'phillips',
        keyTerms: ['Phillips curve', 'short-run Phillips curve (SRPC)', 'long-run Phillips curve (LRPC)', 'expectations-augmented', 'stagflation', 'natural rate hypothesis'],
      },
      {
        id: '3.3.5',
        title: 'Trade-offs between objectives',
        minutes: 7,
        body: [
          'Governments usually want all of: high growth, low unemployment, low inflation, external balance, equity. The objectives can conflict.',
          'Growth vs environment: faster growth may degrade natural capital (negative externality). Sustainability asks whether growth is sustainable over time.',
          'Growth vs equity: growth is not automatically shared — distributional policy may be needed.',
          'Inflation vs unemployment: in the short run, the Phillips trade-off; in the long run, no permanent trade-off.',
        ],
        diagram: null,
        keyTerms: ['trade-off', 'sustainability', 'equity', 'Phillips curve trade-off'],
      },
    ],
  },
  {
    id: '3.4',
    code: '3.4',
    title: 'Inequality and poverty',
    blurb: 'Who gets what — and what governments can do about it.',
    outcomes: [
      'Distinguish between equality and equity, and explain the meaning of economic inequality and poverty.',
      'Construct and interpret a Lorenz curve, and explain the Gini coefficient.',
      'Discuss causes and consequences of inequality, and evaluate policies to reduce it.',
    ],
    lessons: [
      {
        id: '3.4.1',
        title: 'Inequality: income, wealth, and how to measure it',
        minutes: 8,
        body: [
          'Income inequality = unequal distribution of current earnings. Wealth inequality = unequal ownership of assets. The two often overlap but are distinct.',
          'Lorenz curve: plots cumulative share of income (y-axis) against cumulative share of population (x-axis). The further the curve bows from the line of equality, the greater the inequality.',
          'Gini coefficient = area between line of equality and Lorenz curve ÷ total area under line of equality. Ranges from 0 (perfect equality) to 1 (perfect inequality).',
        ],
        diagram: 'lorenz',
        keyTerms: ['income inequality', 'wealth inequality', 'Lorenz curve', 'Gini coefficient'],
      },
      {
        id: '3.4.2',
        title: 'Poverty: absolute, relative, and how to measure it',
        minutes: 6,
        body: [
          'Absolute poverty: unable to afford a minimum standard of living (e.g. international poverty line of $2.15/day at PPP, set by the World Bank).',
          'Relative poverty: income below a threshold relative to the country\'s median (commonly 60% of median equivalised income).',
          'Composite measures like the Multidimensional Poverty Index (MPI) capture health, education and living standards together.',
        ],
        diagram: null,
        keyTerms: ['absolute poverty', 'relative poverty', 'Multidimensional Poverty Index (MPI)', 'international poverty line'],
      },
      {
        id: '3.4.3',
        title: 'Causes and consequences of inequality',
        minutes: 7,
        body: [
          'Causes: inequality of opportunity, unequal resource ownership, different human capital, discrimination, government tax/benefit policy, globalisation, technology-driven skill-biased change.',
          'Consequences: weaker economic growth (poorer human capital, less social mobility), lower living standards for the worst-off, social instability and reduced trust, political polarisation.',
        ],
        diagram: null,
        keyTerms: ['inequality of opportunity', 'human capital', 'skill-biased technical change', 'social mobility'],
      },
      {
        id: '3.4.4',
        title: 'Taxation and redistribution',
        minutes: 8,
        body: [
          'Progressive tax: rate rises with income. Regressive: rate falls with income (typical of indirect taxes like sales tax). Proportional: same rate for all.',
          'Average tax rate = total tax ÷ total income. Marginal tax rate = tax on the next unit of income. Marginal rates matter more for behaviour.',
          'Direct taxes (income, corporate, wealth) and indirect taxes (VAT, excise) have different equity implications. Direct taxes tend to be more progressive.',
        ],
        diagram: null,
        keyTerms: ['progressive tax', 'regressive tax', 'proportional tax', 'average tax rate', 'marginal tax rate', 'direct tax', 'indirect tax'],
      },
      {
        id: '3.4.5',
        title: 'Policies to reduce inequality and poverty',
        minutes: 7,
        body: [
          'Tax-side: progressive income tax, wealth tax, removing tax loopholes, higher minimum wage.',
          'Spending-side: transfer payments (unemployment benefits, pensions, child benefit), targeted spending (means-tested programs), universal basic income.',
          'Investment in human capital: education, healthcare, training, early childhood programs. Reducing discrimination via anti-discrimination law and enforcement.',
          'Evaluate each in terms of equity, efficiency, incentive effects, fiscal cost, and time lags.',
        ],
        diagram: null,
        keyTerms: ['transfer payments', 'universal basic income (UBI)', 'means-tested', 'human capital investment', 'minimum wage'],
      },
    ],
  },
  {
    id: '3.5',
    code: '3.5',
    title: 'Monetary policy',
    blurb: 'How central banks steer the economy by changing the price of money.',
    outcomes: [
      'Explain the goals of monetary policy and the link between interest rates and aggregate demand.',
      '(HL) Explain money creation by commercial banks, and the tools of monetary policy.',
      'Evaluate the effectiveness of monetary policy in achieving macroeconomic objectives.',
    ],
    lessons: [
      {
        id: '3.5.1',
        title: 'Goals of monetary policy',
        minutes: 6,
        body: [
          'Most central banks have a primary mandate: low and stable inflation (typically an explicit target — inflation targeting).',
          'Secondary goals: low unemployment, smoothing the business cycle, supporting long-term growth, external balance.',
          'In practice, the central bank adjusts a short-term policy rate (e.g. base rate, federal funds rate) to influence the whole interest-rate structure.',
        ],
        diagram: null,
        keyTerms: ['monetary policy', 'inflation targeting', 'central bank', 'policy rate', 'base rate'],
      },
      {
        id: '3.5.2',
        title: '(HL) How money is created',
        minutes: 8,
        body: [
          'Most money in modern economies is bank deposits, not physical cash. Commercial banks create deposits by lending.',
          'When a bank makes a loan, it credits the borrower\'s account with a new deposit. The loan creates a new deposit — that is money creation.',
          'The limit on creation is the reserve ratio: banks must hold a fraction of deposits as reserves. The money multiplier links new reserves to the maximum possible new deposits.',
        ],
        formula: 'Maximum new deposits = New reserves × (1 / reserve ratio)',
        diagram: 'moneyMarket',
        keyTerms: ['money creation', 'reserve ratio', 'money multiplier', 'fractional reserve banking'],
      },
      {
        id: '3.5.3',
        title: '(HL) Tools of monetary policy',
        minutes: 8,
        body: [
          'Open market operations: the central bank buys or sells government bonds. Buying bonds injects reserves (expansionary); selling drains them (contractionary).',
          'Minimum reserve requirements: changing the fraction of deposits banks must hold.',
          'Changes to the policy rate (discount/refinancing/base rate): the rate at which the central bank lends to commercial banks. Lower = expansionary.',
          'Quantitative easing (QE): large-scale asset purchases when the policy rate is at the zero lower bound. Aims to lower long-term yields and stimulate demand.',
        ],
        diagram: 'moneyMarket',
        keyTerms: ['open market operations', 'reserve requirements', 'discount rate', 'quantitative easing (QE)', 'zero lower bound'],
      },
      {
        id: '3.5.4',
        title: 'Monetary transmission and AD/AS',
        minutes: 7,
        body: [
          'A cut in the policy rate lowers market interest rates, which raises investment (I) and interest-sensitive consumption (C). AD shifts right.',
          'Lower rates can also weaken the currency, raising net exports (X − M). Higher asset prices raise wealth and consumer confidence.',
          'In AD/AS terms, expansionary monetary policy shifts AD right; contractionary shifts it left.',
        ],
        diagram: 'adas',
        keyTerms: ['monetary transmission mechanism', 'expansionary monetary policy', 'contractionary monetary policy', 'interest rate channel', 'exchange rate channel'],
      },
      {
        id: '3.5.5',
        title: 'Real vs nominal interest rates',
        minutes: 5,
        body: [
          'Nominal interest rate is the rate actually paid. Real interest rate ≈ nominal rate − inflation rate.',
          'Borrowers and lenders care about real rates: the real rate is the actual cost of borrowing or the actual reward for saving.',
          'In a 2% inflation environment, a 5% nominal mortgage has a real rate of about 3%.',
        ],
        formula: 'Real interest rate ≈ Nominal interest rate − Inflation rate',
        diagram: null,
        keyTerms: ['nominal interest rate', 'real interest rate', 'Fisher equation'],
      },
      {
        id: '3.5.6',
        title: 'Effectiveness of monetary policy',
        minutes: 6,
        body: [
          'Strengths: incremental, flexible, easily reversible, short time lags (relative to fiscal).',
          'Constraints: limited scope when rates are near zero (the zero lower bound); low consumer/business confidence can blunt the response; global capital flows can offset domestic rate moves.',
          'Most effective in closing demand-deficient (recessionary) gaps; less effective against supply-side shocks.',
        ],
        diagram: null,
        keyTerms: ['zero lower bound', 'liquidity trap', 'transmission lag'],
      },
    ],
  },
  {
    id: '3.6',
    code: '3.6',
    title: 'Fiscal policy',
    blurb: 'How governments use taxes and spending to steer the economy.',
    outcomes: [
      'Describe the sources of government revenue and types of expenditure.',
      'Explain the goals and transmission of fiscal policy using AD/AS.',
      '(HL) Calculate the Keynesian multiplier and discuss its determinants.',
      'Evaluate the effectiveness of fiscal policy, including constraints like crowding out.',
    ],
    lessons: [
      {
        id: '3.6.1',
        title: 'Government revenue and expenditure',
        minutes: 6,
        body: [
          'Revenue: direct taxes (income, corporate, wealth), indirect taxes (VAT, excise), sale of goods and services from state-owned enterprises, sale of assets, borrowing.',
          'Expenditure: current (salaries, goods, services, interest payments), capital (infrastructure, equipment), transfer payments (pensions, unemployment benefit, child benefit).',
          'A budget deficit = expenditure > revenue. Government (national) debt is the stock of accumulated past deficits.',
        ],
        diagram: null,
        keyTerms: ['budget deficit', 'budget surplus', 'government debt', 'current expenditure', 'capital expenditure', 'transfer payments'],
      },
      {
        id: '3.6.2',
        title: 'Goals and transmission of fiscal policy',
        minutes: 7,
        body: [
          'Goals: low inflation, low unemployment, stable long-term growth, smoothing the cycle, equitable income distribution, external balance.',
          'Expansionary fiscal policy: increase G, cut T, or both. AD shifts right. Used to close a deflationary/recessionary gap.',
          'Contractionary fiscal policy: cut G, raise T, or both. AD shifts left. Used to close an inflationary gap or reduce debt.',
        ],
        diagram: 'adas',
        keyTerms: ['expansionary fiscal policy', 'contractionary fiscal policy', 'fiscal stance', 'automatic stabiliser'],
      },
      {
        id: '3.6.3',
        title: '(HL) The Keynesian multiplier',
        minutes: 10,
        body: [
          'A change in an injection (G, I, X) has a multiplied effect on national income, because each round of spending becomes someone else\'s income, which they partly re-spend.',
          'The size of the multiplier depends on leakages: marginal propensities to save (MPS), tax (MPT), and import (MPM).',
        ],
        formula: 'Multiplier k = 1 / (MPS + MPT + MPM)',
        bodyAfter: [
          'A $1 billion rise in G with MPS = 0.2, MPT = 0.2, MPM = 0.2 → multiplier = 1/0.6 ≈ 1.67, raising GDP by ~$1.67 billion.',
          'Higher leakages = smaller multiplier. Open economies with high MPM have smaller multipliers than closed economies.',
        ],
        diagram: null,
        keyTerms: ['Keynesian multiplier', 'marginal propensity to consume (MPC)', 'marginal propensity to save (MPS)', 'marginal propensity to import (MPM)', 'marginal propensity to tax (MPT)'],
      },
      {
        id: '3.6.4',
        title: 'Automatic stabilisers and discretionary policy',
        minutes: 6,
        body: [
          'Automatic stabilisers: progressive income tax (revenue falls automatically in a downturn) and unemployment benefits (spending rises automatically). They cushion the cycle without any new government action.',
          'Discretionary policy: deliberate changes to G or T decided by the government (e.g. a stimulus package). Slower — political lags, recognition lags, implementation lags.',
        ],
        diagram: null,
        keyTerms: ['automatic stabiliser', 'discretionary fiscal policy', 'implementation lag', 'recognition lag'],
      },
      {
        id: '3.6.5',
        title: '(HL) Crowding out and effectiveness',
        minutes: 7,
        body: [
          'Crowding out: when expansionary fiscal policy raises interest rates and reduces private investment (I), partially offsetting the boost to AD.',
          'More likely in economies near full employment, with high private-sector credit demand, and where the central bank does not accommodate the fiscal expansion.',
          'Effectiveness constraints: political pressure, time lags, sustainable debt, crowding out (HL).',
          'Strengths: can target specific sectors, effective in deep recession when monetary policy is constrained.',
        ],
        diagram: 'crowdingOut',
        keyTerms: ['crowding out', 'sustainable debt', 'debt servicing'],
      },
    ],
  },
  {
    id: '3.7',
    code: '3.7',
    title: 'Supply-side policies',
    blurb: 'Shifting the whole curve right, not just chasing the gap — long-term growth through productivity.',
    outcomes: [
      'Distinguish market-based and interventionist supply-side policies, with examples.',
      'Explain the demand-side and supply-side effects of supply-side policies.',
      'Evaluate the effectiveness of supply-side policies using appropriate criteria.',
    ],
    lessons: [
      {
        id: '3.7.1',
        title: 'Goals of supply-side policy',
        minutes: 5,
        body: [
          'Supply-side policies aim to increase the economy\'s productive capacity over the long term — they shift LRAS (and, in Keynesian models, the long-run AS curve) to the right.',
          'Other goals: improve competition and efficiency, lower labour costs, reduce inflation, raise incentives to invest.',
        ],
        diagram: 'adas',
        keyTerms: ['supply-side policy', 'LRAS shift', 'productive capacity'],
      },
      {
        id: '3.7.2',
        title: 'Market-based policies',
        minutes: 7,
        body: [
          'Pro-competition: deregulation, privatisation, trade liberalisation, anti-monopoly regulation.',
          'Labour market flexibility: weakening trade unions, reducing unemployment benefits, abolishing minimum wages (often criticised for equity effects).',
          'Incentive policies: cuts to personal income tax, business tax, capital gains tax.',
          'Strengths: improved resource allocation, lower burden on government budget. Weaknesses: equity issues, time lags, environmental impact, vested interests.',
        ],
        diagram: 'adas',
        keyTerms: ['deregulation', 'privatisation', 'trade liberalisation', 'labour market flexibility', 'anti-monopoly regulation'],
      },
      {
        id: '3.7.3',
        title: 'Interventionist policies',
        minutes: 6,
        body: [
          'Human capital: education, training, healthcare (quality, quantity, access).',
          'Infrastructure: transport, energy, digital.',
          'Research and development: grants, tax credits, public research bodies.',
          'Industrial policy: targeted support for specific sectors (e.g. semiconductors, green tech).',
          'Strengths: directly supports sectors important for growth. Weaknesses: cost, time lags, government failure risk (picking winners).',
        ],
        diagram: 'adas',
        keyTerms: ['interventionist supply-side policy', 'industrial policy', 'infrastructure investment', 'human capital', 'R&D'],
      },
      {
        id: '3.7.4',
        title: 'Effectiveness of supply-side policies',
        minutes: 6,
        body: [
          'Evaluate using: time lags, fiscal cost, equity impact, sustainability, political feasibility, and how easy the policy is to reverse.',
          'Market-based policies tend to act faster on incentives but raise equity concerns.',
          'Interventionist policies can be precisely targeted but take longer to flow through to LRAS.',
          'A balanced mix is usually best — relying on only one type has predictable limits.',
        ],
        diagram: null,
        keyTerms: ['government failure', 'picking winners', 'time lag (supply-side)'],
      },
    ],
  },
];

// Glossary — every key term used in the course. Order matches first appearance.
export const GLOSSARY = [
  { term: 'Circular flow', definition: 'A model showing the flow of money, goods and services between households, firms, government and the foreign sector, with injections and leakages.' },
  { term: 'Injections', definition: 'Additions to the circular flow: investment (I), government spending (G), and exports (X).' },
  { term: 'Leakages', definition: 'Withdrawals from the circular flow: saving (S), taxes (T), and imports (M).' },
  { term: 'GDP', definition: 'Gross Domestic Product: the market value of all final goods and services produced within a country in a given period.' },
  { term: 'GNI', definition: 'Gross National Income: GDP plus net primary income from abroad.' },
  { term: 'Price deflator', definition: 'A price index (typically with base year = 100) used to convert nominal GDP into real GDP.' },
  { term: 'Net primary income', definition: 'Income earned by residents abroad minus income earned by foreigners domestically.' },
  { term: 'Final goods and services', definition: 'Goods and services sold to the final user; intermediate goods are excluded to avoid double-counting.' },
  { term: 'GDP per capita', definition: 'GDP divided by population. Used to compare average living standards across countries or over time.' },
  { term: 'Purchasing power parity (PPP)', definition: 'An exchange-rate adjustment that equalises the purchasing power of different currencies, so a given amount buys the same bundle of goods everywhere.' },
  { term: 'Business cycle', definition: 'Short-term fluctuations in real GDP around a long-term growth trend, with phases of expansion, peak, contraction and trough.' },
  { term: 'Potential output', definition: 'The level of real GDP consistent with the natural rate of unemployment; also called Yf or full-employment output.' },
  { term: 'Output gap', definition: 'The difference between actual real GDP and potential output. Positive gap = above potential; negative gap = below potential (recessionary).' },
  { term: 'Recession', definition: 'A significant decline in real GDP for two or more consecutive quarters (common rule of thumb).' },
  { term: 'Expansion', definition: 'A phase of the business cycle in which real GDP is rising.' },
  { term: 'Peak', definition: 'The turning point at which an expansion ends and a contraction begins.' },
  { term: 'Trough', definition: 'The turning point at which a contraction ends and an expansion begins.' },
  { term: 'OECD Better Life Index', definition: 'An index measuring well-being across 11 dimensions (housing, income, jobs, community, education, environment, civic engagement, health, life satisfaction, safety, work-life balance).' },
  { term: 'Human Development Index (HDI)', definition: 'A composite index of life expectancy, education and per-capita income.' },
  { term: 'Happy Planet Index', definition: 'An index that weights life satisfaction and life expectancy by ecological footprint, capturing sustainable well-being.' },
  { term: 'Aggregate demand (AD)', definition: 'The total quantity of real output demanded at each price level; AD = C + I + G + (X − M).' },
  { term: 'Real balances effect', definition: 'The component of the AD slope driven by changes in the real value of money holdings as the price level changes.' },
  { term: 'Interest rate effect', definition: 'The component of the AD slope driven by changes in interest rates (and hence investment) as the price level changes.' },
  { term: 'International competitiveness effect', definition: 'The component of the AD slope driven by changes in net exports as the price level changes exchange-rate competitiveness.' },
  { term: 'Short-run aggregate supply (SRAS)', definition: 'The total quantity of real output supplied at each price level in the short run, when some input prices (especially nominal wages) are sticky.' },
  { term: 'Sticky wages', definition: 'The observation that nominal wages adjust slowly to changes in economic conditions, producing a positively-sloped SRAS.' },
  { term: 'Cost-push shock', definition: 'An increase in production costs (e.g. oil price) that shifts SRAS leftward, raising prices and lowering output.' },
  { term: 'Favourable supply shock', definition: 'A decrease in production costs or an increase in productivity that shifts SRAS rightward, lowering prices and raising output.' },
  { term: 'Long-run aggregate supply (LRAS)', definition: 'A vertical curve at potential output in the monetarist/new classical model, representing the economy\'s productive capacity.' },
  { term: 'Natural rate of unemployment', definition: 'The unemployment rate consistent with potential output, equal to the sum of structural, frictional and seasonal unemployment.' },
  { term: 'Monetarist', definition: 'A school of thought that emphasises the role of money supply and expects the economy to self-correct to potential output in the long run.' },
  { term: 'New classical', definition: 'A school of thought combining monetarist long-run neutrality with rational expectations; LRAS is vertical at the natural rate.' },
  { term: 'Keynesian', definition: 'A school of thought arguing that prices and wages are sticky, so the economy can remain below potential for extended periods without policy intervention.' },
  { term: 'Vertical LRAS', definition: 'A graphical representation of the monetarist view that long-run output is independent of the price level.' },
  { term: 'Short-run equilibrium', definition: 'The intersection of AD and SRAS, giving current real output and price level.' },
  { term: 'Long-run equilibrium', definition: 'Output at potential (Y = Yf) with the price level determined by the AD curve at Yf.' },
  { term: 'Self-correction', definition: 'The mechanism (in monetarist models) by which the economy returns to potential output through wage and price adjustment.' },
  { term: 'Inflationary gap', definition: 'A situation in which short-run equilibrium output exceeds potential output (positive output gap).' },
  { term: 'Deflationary gap', definition: 'A situation in which short-run equilibrium output is below potential output (negative output gap). Also called a recessionary gap.' },
  { term: 'Recessionary gap', definition: 'Same as deflationary gap: equilibrium output is below potential output.' },
  { term: 'Economic growth', definition: 'An increase in the productive capacity of the economy (long-run growth) or actual real GDP (short-run growth).' },
  { term: 'Short-term growth', definition: 'Growth driven by an outward shift of AD, raising actual real GDP and possibly the price level.' },
  { term: 'Long-term growth', definition: 'Growth driven by an outward shift of LRAS, raising potential output.' },
  { term: 'LRAS shift', definition: 'A rightward shift of LRAS caused by more or better factors of production, technological progress, or improved efficiency.' },
  { term: 'PPC shift', definition: 'A rightward shift of the production possibilities curve, representing growth in production possibilities.' },
  { term: 'Unemployment rate', definition: 'The number of unemployed people divided by the labour force, expressed as a percentage.' },
  { term: 'Labour force', definition: 'The sum of employed and unemployed people who are actively seeking work; excludes those not seeking work (e.g. students, retirees, discouraged workers).' },
  { term: 'Cyclical unemployment', definition: 'Unemployment caused by a downturn in aggregate demand; rises during recessions and falls during expansions.' },
  { term: 'Structural unemployment', definition: 'Unemployment caused by a mismatch between workers\' skills (or locations) and the skills (or locations) demanded by employers.' },
  { term: 'Frictional unemployment', definition: 'Short-run unemployment while workers transition between jobs or enter the labour force.' },
  { term: 'Seasonal unemployment', definition: 'Unemployment caused by predictable changes in demand across the year (e.g. tourism, agriculture).' },
  { term: 'Inflation', definition: 'A sustained increase in the general price level.' },
  { term: 'Deflation', definition: 'A sustained decrease in the general price level.' },
  { term: 'Disinflation', definition: 'A decrease in the inflation rate (the rate at which prices are rising slows down).' },
  { term: 'CPI', definition: 'Consumer Price Index: a weighted average of the prices of a basket of consumer goods and services, used to track inflation.' },
  { term: 'Demand-pull inflation', definition: 'Inflation caused by AD rising faster than AS, often associated with growth above potential.' },
  { term: 'Cost-push inflation', definition: 'Inflation caused by a leftward shift of SRAS (e.g. higher oil prices), with output falling — stagflation.' },
  { term: 'Stagflation', definition: 'A combination of stagnant or falling output and rising prices, typically caused by an adverse supply shock.' },
  { term: 'Phillips curve', definition: 'A curve showing the relationship between the inflation rate and the unemployment rate.' },
  { term: 'Short-run Phillips curve (SRPC)', definition: 'A downward-sloping curve showing the inverse short-run relationship between inflation and unemployment.' },
  { term: 'Long-run Phillips curve (LRPC)', definition: 'A vertical curve at the natural rate of unemployment, reflecting the long-run neutrality of inflation.' },
  { term: 'Expectations-augmented', definition: 'A version of the Phillips curve in which the SRPC shifts when expected inflation changes.' },
  { term: 'Stagflation', definition: 'A combination of high inflation and high unemployment (see cost-push inflation).' },
  { term: 'Natural rate hypothesis', definition: 'The proposition that in the long run the economy returns to the natural rate of unemployment regardless of the inflation rate.' },
  { term: 'Trade-off', definition: 'A situation in which improving one objective (e.g. lower inflation) requires worsening another (e.g. higher unemployment in the short run).' },
  { term: 'Sustainability', definition: 'The ability of growth or other economic activity to be maintained over time without depleting natural, human or social capital.' },
  { term: 'Equity', definition: 'Fairness in the distribution of resources, opportunities or outcomes; distinct from equality (which is treating everyone the same).' },
  { term: 'Income inequality', definition: 'The unequal distribution of current income across households or individuals.' },
  { term: 'Wealth inequality', definition: 'The unequal distribution of asset ownership across households or individuals.' },
  { term: 'Lorenz curve', definition: 'A graph plotting cumulative share of income (y-axis) against cumulative share of population (x-axis); the further it bows from the 45° line, the more unequal the distribution.' },
  { term: 'Gini coefficient', definition: 'A number between 0 and 1 measuring inequality; 0 = perfect equality, 1 = perfect inequality. Calculated from the Lorenz curve.' },
  { term: 'Absolute poverty', definition: 'Inability to afford a minimum standard of living; often defined relative to an international poverty line (e.g. $2.15/day at PPP).' },
  { term: 'Relative poverty', definition: 'Income below a threshold defined relative to a country\'s typical income (e.g. below 60% of median income).' },
  { term: 'Multidimensional Poverty Index (MPI)', definition: 'A composite measure of poverty across health, education and living standards.' },
  { term: 'International poverty line', definition: 'A monetary threshold (set by the World Bank) below which a person is considered to be in extreme poverty, expressed at PPP.' },
  { term: 'Inequality of opportunity', definition: 'Inequality arising from factors outside an individual\'s control (family background, birthplace, gender, race).' },
  { term: 'Human capital', definition: 'The skills, knowledge, health and experience embodied in workers, which raise their productivity.' },
  { term: 'Skill-biased technical change', definition: 'Technological progress that raises the demand for skilled workers relative to unskilled workers, widening wage inequality.' },
  { term: 'Social mobility', definition: 'The degree to which individuals move up or down the income distribution over their lifetime or across generations.' },
  { term: 'Progressive tax', definition: 'A tax whose average rate rises with the taxpayer\'s income.' },
  { term: 'Regressive tax', definition: 'A tax whose average rate falls as income rises (typical of indirect taxes on consumption).' },
  { term: 'Proportional tax', definition: 'A tax whose rate is the same for all taxpayers, regardless of income.' },
  { term: 'Average tax rate', definition: 'Total tax paid divided by total income.' },
  { term: 'Marginal tax rate', definition: 'The tax rate applied to the next unit of income; affects behaviour more than the average rate.' },
  { term: 'Direct tax', definition: 'A tax levied directly on income or wealth (e.g. income tax, corporate tax, wealth tax).' },
  { term: 'Indirect tax', definition: 'A tax levied on spending (e.g. VAT, excise duty), usually regressive.' },
  { term: 'Transfer payments', definition: 'Government payments to individuals for which no good or service is received in return (e.g. pensions, unemployment benefit, child benefit).' },
  { term: 'Universal basic income (UBI)', definition: 'A regular cash payment from the government to every adult, regardless of income or employment status.' },
  { term: 'Means-tested', definition: 'A benefit or service available only to those whose income or assets fall below a defined threshold.' },
  { term: 'Minimum wage', definition: 'A legal floor on the hourly wage rate; can raise the wage of low-paid workers but may also reduce employment if set above the equilibrium.' },
  { term: 'Monetary policy', definition: 'Policy set by the central bank, typically adjusting short-term interest rates, to influence macroeconomic outcomes.' },
  { term: 'Inflation targeting', definition: 'A monetary policy framework in which the central bank announces an explicit inflation target and adjusts the policy rate to hit it.' },
  { term: 'Central bank', definition: 'A public institution that issues currency, manages the money supply and sets the policy rate (e.g. the Federal Reserve, ECB, Bank of England).' },
  { term: 'Policy rate', definition: 'The short-term interest rate set by the central bank, which anchors the structure of market interest rates.' },
  { term: 'Base rate', definition: 'The interest rate at which the central bank lends to commercial banks; synonymous with policy rate / discount rate / refinancing rate (in different jurisdictions).' },
  { term: 'Money creation', definition: 'The process by which commercial banks create new deposits when they make loans, expanding the money supply.' },
  { term: 'Reserve ratio', definition: 'The fraction of customer deposits that a commercial bank must hold as reserves.' },
  { term: 'Money multiplier', definition: 'The ratio of new deposits created to new reserves; equal to 1 ÷ reserve ratio in the simplest model.' },
  { term: 'Fractional reserve banking', definition: 'A banking system in which banks hold only a fraction of deposits as reserves and lend the rest.' },
  { term: 'Open market operations', definition: 'The central bank\'s buying or selling of government bonds to change the money supply and the policy rate.' },
  { term: 'Reserve requirements', definition: 'Regulations requiring banks to hold a minimum fraction of deposits as reserves; raising the ratio is contractionary, lowering it expansionary.' },
  { term: 'Discount rate', definition: 'The rate at which the central bank lends directly to commercial banks; lowering it is expansionary.' },
  { term: 'Quantitative easing (QE)', definition: 'Large-scale asset purchases by the central bank, used when the policy rate is near its zero lower bound, to lower long-term interest rates.' },
  { term: 'Zero lower bound', definition: 'The constraint that nominal interest rates cannot fall much below zero, limiting conventional monetary policy.' },
  { term: 'Monetary transmission mechanism', definition: 'The chain of effects through which a change in the policy rate affects aggregate demand and the economy.' },
  { term: 'Expansionary monetary policy', definition: 'Policy that lowers interest rates or expands the money supply to raise AD.' },
  { term: 'Contractionary monetary policy', definition: 'Policy that raises interest rates or contracts the money supply to lower AD.' },
  { term: 'Interest rate channel', definition: 'The part of the monetary transmission mechanism that runs from the policy rate to investment, durable consumption and housing demand.' },
  { term: 'Exchange rate channel', definition: 'The part of the monetary transmission mechanism that runs from the policy rate to the exchange rate and hence to net exports.' },
  { term: 'Nominal interest rate', definition: 'The interest rate expressed in current money terms, with no adjustment for inflation.' },
  { term: 'Real interest rate', definition: 'The interest rate adjusted for inflation; approximately equal to the nominal rate minus the inflation rate.' },
  { term: 'Fisher equation', definition: 'The relationship r ≈ i − π, linking real, nominal and inflation rates.' },
  { term: 'Liquidity trap', definition: 'A situation in which conventional monetary policy is ineffective because interest rates are at or near the zero lower bound.' },
  { term: 'Transmission lag', definition: 'The delay between a monetary policy action and its effect on the real economy.' },
  { term: 'Budget deficit', definition: 'Annual government expenditure exceeding annual revenue.' },
  { term: 'Budget surplus', definition: 'Annual government revenue exceeding annual expenditure.' },
  { term: 'Government debt', definition: 'The stock of accumulated past government borrowing; the sum of all past deficits minus surpluses.' },
  { term: 'Current expenditure', definition: 'Government spending on goods, services and wages consumed within the year.' },
  { term: 'Capital expenditure', definition: 'Government spending on assets that provide value over multiple years (infrastructure, equipment).' },
  { term: 'Expansionary fiscal policy', definition: 'Policy that increases aggregate demand by raising government spending or cutting taxes.' },
  { term: 'Contractionary fiscal policy', definition: 'Policy that reduces aggregate demand by cutting government spending or raising taxes.' },
  { term: 'Fiscal stance', definition: 'The overall direction of fiscal policy: expansionary, contractionary or neutral.' },
  { term: 'Automatic stabiliser', definition: 'A feature of the tax-and-transfer system that automatically dampens the business cycle without new government action (e.g. progressive tax, unemployment benefits).' },
  { term: 'Keynesian multiplier', definition: 'The ratio of a change in national income to the initial change in autonomous spending that caused it; equal to 1 / (MPS + MPT + MPM).' },
  { term: 'Marginal propensity to consume (MPC)', definition: 'The fraction of an extra unit of income that households spend on consumption.' },
  { term: 'Marginal propensity to save (MPS)', definition: 'The fraction of an extra unit of income that households save. MPS = 1 − MPC (in a closed economy with no taxes).' },
  { term: 'Marginal propensity to import (MPM)', definition: 'The fraction of an extra unit of income that households spend on imports.' },
  { term: 'Marginal propensity to tax (MPT)', definition: 'The fraction of an extra unit of income that is collected in tax.' },
  { term: 'Discretionary fiscal policy', definition: 'Deliberate changes to government spending or taxation decided by the government.' },
  { term: 'Implementation lag', definition: 'The delay between recognising a need for fiscal action and implementing the policy.' },
  { term: 'Recognition lag', definition: 'The delay before policymakers recognise that the economy needs fiscal action.' },
  { term: 'Crowding out', definition: 'A reduction in private-sector spending (usually investment) caused by an expansionary fiscal policy raising interest rates.' },
  { term: 'Sustainable debt', definition: 'A level of government debt that can be serviced without forcing disruptive adjustments to fiscal policy.' },
  { term: 'Debt servicing', definition: 'The interest payments the government makes on its outstanding debt.' },
  { term: 'Supply-side policy', definition: 'Policy aimed at raising the economy\'s long-term productive capacity (shifting LRAS rightward).' },
  { term: 'Productive capacity', definition: 'The maximum sustainable level of real output the economy can produce.' },
  { term: 'Deregulation', definition: 'Removing or simplifying government regulations, typically to encourage competition and reduce costs.' },
  { term: 'Privatisation', definition: 'The transfer of state-owned enterprises to private ownership.' },
  { term: 'Trade liberalisation', definition: 'The reduction of barriers to international trade (tariffs, quotas), typically expansionary for AD and SRAS.' },
  { term: 'Labour market flexibility', definition: 'Policies that make it easier to hire and fire workers, often by weakening unions or cutting unemployment benefits.' },
  { term: 'Anti-monopoly regulation', definition: 'Rules preventing firms from abusing market power, intended to keep markets competitive.' },
  { term: 'Interventionist supply-side policy', definition: 'Government investment in human capital, infrastructure, R&D, or specific industries to raise long-run productivity.' },
  { term: 'Industrial policy', definition: 'Targeted government support for specific industries considered important for long-term growth.' },
  { term: 'Infrastructure investment', definition: 'Public spending on transport, energy, digital and other foundational assets that raise economy-wide productivity.' },
  { term: 'Human capital', definition: 'See entry above. In the supply-side context, the focus is on policies that raise the stock of human capital.' },
  { term: 'R&D', definition: 'Research and development: investment in creating new products, processes and knowledge.' },
  { term: 'Government failure', definition: 'A situation in which government intervention makes outcomes worse than the market alone would have produced.' },
  { term: 'Picking winners', definition: 'Criticism of industrial policy: that governments lack the information to identify which firms or industries will succeed.' },
  { term: 'Time lag (supply-side)', definition: 'The delay between introducing a supply-side policy and seeing its effect on LRAS and output.' },
];
