// macrow course content — sourced from IBDP Economics syllabus, Unit 3 (Macroeconomics).
// Each module corresponds to a syllabus sub-topic (3.1 – 3.7). Each module has lessons
// (concept explanation + linked diagram + practice questions). Glossary entries are
// the canonical definitions.

export const COURSE = [
  {
    id: '3.1',
    code: '3.1',
    title: 'Measuring economic activity',
    blurb: 'How we count what an economy produces, and why the headcount is more than a number.',
    outcomes: [
      'Explain the equivalence of income, output and expenditure approaches using the circular flow.',
      'Distinguish nominal from real GDP and GNI, and calculate real values using a price deflator.',
      'Discuss the appropriateness of GDP/GNI for measuring well-being, with reference to alternative indices.',
    ],
    lessons: [
      {
        id: '3.1.1',
        title: 'The circular flow of income',
        minutes: 8,
        body: [
          'The circular flow shows how money, goods and services move between households, firms, the government and the foreign sector.',
          'Injections (investment, government spending, exports) add to the flow; leakages (saving, taxes, imports) drain it. In equilibrium injections equal leakages.',
          'The three approaches to national income — output, income and expenditure — give the same total because every transaction is both a payment and a receipt.',
        ],
        diagram: 'circularFlow',
        keyTerms: ['circular flow', 'injections', 'leakages', 'expenditure approach', 'income approach', 'output approach'],
      },
      {
        id: '3.1.2',
        title: 'GDP, GNI, and the difference between them',
        minutes: 7,
        body: [
          'Gross Domestic Product (GDP) measures the total market value of all final goods and services produced within a country in a period.',
          'Gross National Income (GNI) = GDP + net primary income from abroad (income residents earn overseas minus income foreigners earn domestically).',
          'Both can be reported nominal (at current prices) or real (adjusted for inflation using a price deflator). Real values are what allow comparisons over time.',
        ],
        formula: 'Real GDP = (Nominal GDP / Price deflator) × 100',
        diagram: null,
        keyTerms: ['GDP', 'GNI', 'price deflator', 'net primary income', 'final goods and services'],
      },
      {
        id: '3.1.3',
        title: 'Per capita measures and cross-country comparisons',
        minutes: 6,
        body: [
          'Real GDP per capita = Real GDP / Population. Useful for comparing average living standards.',
          'Purchasing Power Parity (PPP) adjusts for differences in price levels across countries, so a dollar buys the same bundle everywhere.',
          'GDP/GNI per capita at PPP is the standard cross-country welfare comparison, but it still misses inequality, environment, and unpaid work.',
        ],
        diagram: null,
        keyTerms: ['GDP per capita', 'purchasing power parity (PPP)'],
      },
      {
        id: '3.1.4',
        title: 'The business cycle and potential output',
        minutes: 9,
        body: [
          'Real GDP fluctuates around a long-term growth trend. The business cycle has four phases: expansion, peak, contraction (recession), trough.',
          'Potential output (Yf) is the level of real GDP consistent with the natural rate of unemployment. The output gap is the difference between actual and potential output.',
          'Recessionary gap: actual < potential. Inflationary gap: actual > potential (Keynesian view; some schools call this a positive output gap).',
        ],
        diagram: 'businessCycle',
        keyTerms: ['business cycle', 'potential output', 'output gap', 'recession', 'expansion', 'peak', 'trough'],
      },
      {
        id: '3.1.5',
        title: 'Beyond GDP — measuring well-being',
        minutes: 6,
        body: [
          'GDP is a measure of output, not welfare. It ignores income distribution, non-market work, environmental damage, and quality of life.',
          'Alternative indices: OECD Better Life Index (11 dimensions), UN Human Development Index, Happy Planet Index (life expectancy × well-being ÷ ecological footprint).',
          'For exam answers: GDP is useful but limited; complement it with at least one alternative index when evaluating well-being.',
        ],
        diagram: null,
        keyTerms: ['OECD Better Life Index', 'Human Development Index (HDI)', 'Happy Planet Index'],
      },
    ],
  },
  {
    id: '3.2',
    code: '3.2',
    title: 'Aggregate demand and aggregate supply',
    blurb: 'The two curves that frame every macro story: what shifts them, and what happens at the intersection.',
    outcomes: [
      'Construct and interpret AD and AS diagrams, including shifts caused by their determinants.',
      'Compare monetarist/new classical and Keynesian views of aggregate supply in the short run and long run.',
      'Explain short-run and long-run macroeconomic equilibrium, including the concepts of inflationary and deflationary gaps.',
    ],
    lessons: [
      {
        id: '3.2.1',
        title: 'The aggregate demand curve',
        minutes: 8,
        body: [
          'Aggregate demand (AD) is the total quantity of real output demanded at each price level. It slopes downward.',
          'AD = C + I + G + (X − M). The downward slope reflects three effects: real balances, interest rate, and international competitiveness.',
          'Determinants of the components:',
        ],
        bullets: [
          'C: consumer confidence, interest rates, wealth, income taxes, household debt, expected future prices.',
          'I: interest rates, business confidence, technology, business taxes, corporate debt.',
          'G: political and economic priorities.',
          'X − M: income of trading partners, exchange rates, trade policies.',
        ],
        diagram: 'ad',
        keyTerms: ['aggregate demand (AD)', 'real balances effect', 'interest rate effect', 'international competitiveness effect'],
      },
      {
        id: '3.2.2',
        title: 'The short-run aggregate supply (SRAS) curve',
        minutes: 7,
        body: [
          'SRAS slopes upward in the short run: higher prices encourage firms to expand output because nominal wages and some input prices are sticky.',
          'Determinants of SRAS: costs of factors of production, indirect taxes, productivity shocks, supply shocks (e.g. oil price).',
          'A rightward shift of SRAS = favourable supply shock (lower costs or higher productivity). A leftward shift = adverse supply shock (cost-push inflation).',
        ],
        diagram: 'sras',
        keyTerms: ['short-run aggregate supply (SRAS)', 'sticky wages', 'cost-push shock', 'favourable supply shock'],
      },
      {
        id: '3.2.3',
        title: 'Two views of long-run aggregate supply',
        minutes: 10,
        body: [
          'Monetarist / new classical view: LRAS is vertical at the natural rate of unemployment. Markets clear; output returns to potential in the long run regardless of AD.',
          'Keynesian view: AS can slope upward over the long term too, because wages and prices adjust slowly. Persistent deflationary gaps are possible.',
          'Both views accept that the economy can deviate from potential in the short run — they disagree on how quickly (or whether) it returns.',
        ],
        diagram: 'lras',
        keyTerms: ['long-run aggregate supply (LRAS)', 'natural rate of unemployment', 'monetarist', 'new classical', 'Keynesian', 'vertical LRAS'],
      },
      {
        id: '3.2.4',
        title: 'Macroeconomic equilibrium: short run and long run',
        minutes: 10,
        body: [
          'Short-run equilibrium: AD = SRAS at the current price level. This gives actual output Y and price level P.',
          'In the monetarist model, the economy self-corrects: if Y > Yf, nominal wages and prices rise, SRAS shifts left until output returns to potential at a higher price.',
          'In the Keynesian model, this adjustment may be slow or incomplete — leaving persistent deflationary gaps that require active policy.',
        ],
        diagram: 'equilibrium',
        keyTerms: ['short-run equilibrium', 'long-run equilibrium', 'self-correction', 'inflationary gap', 'deflationary gap', 'recessionary gap'],
      },
    ],
  },
  {
    id: '3.3',
    code: '3.3',
    title: 'Macroeconomic objectives',
    blurb: 'What governments want: growth, low unemployment, low inflation, balance — and the trade-offs between them.',
    outcomes: [
      'Measure and explain economic growth, unemployment and inflation, including their causes and consequences.',
      'Discuss the trade-offs between the main macroeconomic objectives.',
      '(HL) Discuss the Phillips curve, including the short-run and long-run relationship between inflation and unemployment.',
    ],
    lessons: [
      {
        id: '3.3.1',
        title: 'Economic growth: short-term and long-term',
        minutes: 8,
        body: [
          'Short-term growth is driven by AD. In the AD/AS model, an outward shift of AD raises real output (and prices) in the short run.',
          'Long-term growth is driven by LRAS — the productive capacity of the economy. It requires more or better factors of production, better technology, improved efficiency, and supportive institutions.',
          'PPC shifts outward with growth in production possibilities. In AD/AS terms, LRAS shifts right.',
        ],
        diagram: 'growth',
        keyTerms: ['economic growth', 'short-term growth', 'long-term growth', 'LRAS shift', 'PPC shift'],
      },
      {
        id: '3.3.2',
        title: 'Unemployment: types, measures, costs',
        minutes: 9,
        body: [
          'Unemployment rate = (unemployed ÷ labour force) × 100. The labour force excludes those not actively seeking work.',
          'Types of unemployment:',
        ],
        bullets: [
          'Cyclical (demand-deficient) — falls in AD, associated with recessionary gaps.',
          'Structural — skills mismatch or geographic mismatch between workers and jobs.',
          'Seasonal — predictable variation across the year (e.g. tourism, agriculture).',
          'Frictional — short-run unemployment while workers transition between jobs.',
        ],
        bodyAfter: [
          'The natural rate of unemployment is the sum of structural, seasonal and frictional unemployment — it persists even at potential output.',
          'Costs: personal (income, health, skills), social (inequality, exclusion), economic (lost output, lower tax revenue).',
        ],
        diagram: 'unemployment',
        keyTerms: ['unemployment rate', 'labour force', 'cyclical unemployment', 'structural unemployment', 'frictional unemployment', 'seasonal unemployment', 'natural rate of unemployment'],
      },
      {
        id: '3.3.3',
        title: 'Inflation: causes, measures, costs',
        minutes: 10,
        body: [
          'Inflation is a sustained rise in the general price level. Measured using the Consumer Price Index (CPI): a weighted basket of goods and services.',
          'Causes:',
        ],
        bullets: [
          'Demand-pull — AD rises faster than AS. Often associated with rapid growth above potential.',
          'Cost-push — SRAS shifts left (e.g. oil shock, wage-price spiral). Output falls, prices rise — stagflation.',
        ],
        bodyAfter: [
          'Costs of high inflation: uncertainty, redistributive effects, damaged export competitiveness, lower saving, inefficient resource allocation, slower growth.',
          'Disinflation is a fall in the inflation rate; deflation is a sustained fall in prices. Deflation raises the real value of debt and can cause a debt-deflation spiral.',
          'CPI limitations: quality change, new products, substitution bias, different spending patterns across households.',
        ],
        diagram: 'inflation',
        keyTerms: ['inflation', 'deflation', 'disinflation', 'CPI', 'demand-pull inflation', 'cost-push inflation', 'stagflation'],
      },
      {
        id: '3.3.4',
        title: '(HL) The Phillips curve',
        minutes: 12,
        body: [
          'The Phillips curve shows the inverse relationship between the rate of inflation and the rate of unemployment.',
          'Short-run Phillips curve (SRPC): downward sloping. Policymakers face a trade-off — accept higher inflation to lower unemployment (or vice versa).',
          'Long-run Phillips curve (LRPC): vertical at the natural rate of unemployment. In the long run, attempts to push unemployment below the natural rate only produce accelerating inflation.',
          'Expectations-augmented view: the SRPC shifts when expected inflation changes. The 1970s stagflation episode (high inflation + high unemployment) is the standard example.',
        ],
        diagram: 'phillips',
        keyTerms: ['Phillips curve', 'short-run Phillips curve (SRPC)', 'long-run Phillips curve (LRPC)', 'expectations-augmented', 'stagflation', 'natural rate hypothesis'],
      },
      {
        id: '3.3.5',
        title: 'Trade-offs between objectives',
        minutes: 7,
        body: [
          'Governments usually want all of: high growth, low unemployment, low inflation, external balance, equity. The objectives can conflict.',
          'Growth vs environment: faster growth may degrade natural capital (negative externality). Sustainability asks whether growth is sustainable over time.',
          'Growth vs equity: growth is not automatically shared — distributional policy may be needed.',
          'Inflation vs unemployment: in the short run, the Phillips trade-off; in the long run, no permanent trade-off.',
        ],
        diagram: null,
        keyTerms: ['trade-off', 'sustainability', 'equity', 'Phillips curve trade-off'],
      },
    ],
  },
  {
    id: '3.4',
    code: '3.4',
    title: 'Inequality and poverty',
    blurb: 'Who gets what — and what governments can do about it.',
    outcomes: [
      'Distinguish between equality and equity, and explain the meaning of economic inequality and poverty.',
      'Construct and interpret a Lorenz curve, and explain the Gini coefficient.',
      'Discuss causes and consequences of inequality, and evaluate policies to reduce it.',
    ],
    lessons: [
      {
        id: '3.4.1',
        title: 'Inequality: income, wealth, and how to measure it',
        minutes: 8,
        body: [
          'Income inequality = unequal distribution of current earnings. Wealth inequality = unequal ownership of assets. The two often overlap but are distinct.',
          'Lorenz curve: plots cumulative share of income (y-axis) against cumulative share of population (x-axis). The further the curve bows from the line of equality, the greater the inequality.',
          'Gini coefficient = area between line of equality and Lorenz curve ÷ total area under line of equality. Ranges from 0 (perfect equality) to 1 (perfect inequality).',
        ],
        diagram: 'lorenz',
        keyTerms: ['income inequality', 'wealth inequality', 'Lorenz curve', 'Gini coefficient'],
      },
      {
        id: '3.4.2',
        title: 'Poverty: absolute, relative, and how to measure it',
        minutes: 6,
        body: [
          'Absolute poverty: unable to afford a minimum standard of living (e.g. international poverty line of $2.15/day at PPP, set by the World Bank).',
          'Relative poverty: income below a threshold relative to the country\'s median (commonly 60% of median equivalised income).',
          'Composite measures like the Multidimensional Poverty Index (MPI) capture health, education and living standards together.',
        ],
        diagram: null,
        keyTerms: ['absolute poverty', 'relative poverty', 'Multidimensional Poverty Index (MPI)', 'international poverty line'],
      },
      {
        id: '3.4.3',
        title: 'Causes and consequences of inequality',
        minutes: 7,
        body: [
          'Causes: inequality of opportunity, unequal resource ownership, different human capital, discrimination, government tax/benefit policy, globalisation, technology-driven skill-biased change.',
          'Consequences: weaker economic growth (poorer human capital, less social mobility), lower living standards for the worst-off, social instability and reduced trust, political polarisation.',
        ],
        diagram: null,
        keyTerms: ['inequality of opportunity', 'human capital', 'skill-biased technical change', 'social mobility'],
      },
      {
        id: '3.4.4',
        title: 'Taxation and redistribution',
        minutes: 8,
        body: [
          'Progressive tax: rate rises with income. Regressive: rate falls with income (typical of indirect taxes like sales tax). Proportional: same rate for all.',
          'Average tax rate = total tax ÷ total income. Marginal tax rate = tax on the next unit of income. Marginal rates matter more for behaviour.',
          'Direct taxes (income, corporate, wealth) and indirect taxes (VAT, excise) have different equity implications. Direct taxes tend to be more progressive.',
        ],
        diagram: null,
        keyTerms: ['progressive tax', 'regressive tax', 'proportional tax', 'average tax rate', 'marginal tax rate', 'direct tax', 'indirect tax'],
      },
      {
        id: '3.4.5',
        title: 'Policies to reduce inequality and poverty',
        minutes: 7,
        body: [
          'Tax-side: progressive income tax, wealth tax, removing tax loopholes, higher minimum wage.',
          'Spending-side: transfer payments (unemployment benefits, pensions, child benefit), targeted spending (means-tested programs), universal basic income.',
          'Investment in human capital: education, healthcare, training, early childhood programs. Reducing discrimination via anti-discrimination law and enforcement.',
          'Evaluate each in terms of equity, efficiency, incentive effects, fiscal cost, and time lags.',
        ],
        diagram: null,
        keyTerms: ['transfer payments', 'universal basic income (UBI)', 'means-tested', 'human capital investment', 'minimum wage'],
      },
    ],
  },
  {
    id: '3.5',
    code: '3.5',
    title: 'Monetary policy',
    blurb: 'How central banks steer the economy by changing the price of money.',
    outcomes: [
      'Explain the goals of monetary policy and the link between interest rates and aggregate demand.',
      '(HL) Explain money creation by commercial banks, and the tools of monetary policy.',
      'Evaluate the effectiveness of monetary policy in achieving macroeconomic objectives.',
    ],
    lessons: [
      {
        id: '3.5.1',
        title: 'Goals of monetary policy',
        minutes: 6,
        body: [
          'Most central banks have a primary mandate: low and stable inflation (typically an explicit target — inflation targeting).',
          'Secondary goals: low unemployment, smoothing the business cycle, supporting long-term growth, external balance.',
          'In practice, the central bank adjusts a short-term policy rate (e.g. base rate, federal funds rate) to influence the whole interest-rate structure.',
        ],
        diagram: null,
        keyTerms: ['monetary policy', 'inflation targeting', 'central bank', 'policy rate', 'base rate'],
      },
      {
        id: '3.5.2',
        title: '(HL) How money is created',
        minutes: 8,
        body: [
          'Most money in modern economies is bank deposits, not physical cash. Commercial banks create deposits by lending.',
          'When a bank makes a loan, it credits the borrower\'s account with a new deposit. The loan creates a new deposit — that is money creation.',
          'The limit on creation is the reserve ratio: banks must hold a fraction of deposits as reserves. The money multiplier links new reserves to the maximum possible new deposits.',
        ],
        formula: 'Maximum new deposits = New reserves × (1 / reserve ratio)',
        diagram: 'moneyMarket',
        keyTerms: ['money creation', 'reserve ratio', 'money multiplier', 'fractional reserve banking'],
      },
      {
        id: '3.5.3',
        title: '(HL) Tools of monetary policy',
        minutes: 8,
        body: [
          'Open market operations: the central bank buys or sells government bonds. Buying bonds injects reserves (expansionary); selling drains them (contractionary).',
          'Minimum reserve requirements: changing the fraction of deposits banks must hold.',
          'Changes to the policy rate (discount/refinancing/base rate): the rate at which the central bank lends to commercial banks. Lower = expansionary.',
          'Quantitative easing (QE): large-scale asset purchases when the policy rate is at the zero lower bound. Aims to lower long-term yields and stimulate demand.',
        ],
        diagram: 'moneyMarket',
        keyTerms: ['open market operations', 'reserve requirements', 'discount rate', 'quantitative easing (QE)', 'zero lower bound'],
      },
      {
        id: '3.5.4',
        title: 'Monetary transmission and AD/AS',
        minutes: 7,
        body: [
          'A cut in the policy rate lowers market interest rates, which raises investment (I) and interest-sensitive consumption (C). AD shifts right.',
          'Lower rates can also weaken the currency, raising net exports (X − M). Higher asset prices raise wealth and consumer confidence.',
          'In AD/AS terms, expansionary monetary policy shifts AD right; contractionary shifts it left.',
        ],
        diagram: 'adas',
        keyTerms: ['monetary transmission mechanism', 'expansionary monetary policy', 'contractionary monetary policy', 'interest rate channel', 'exchange rate channel'],
      },
      {
        id: '3.5.5',
        title: 'Real vs nominal interest rates',
        minutes: 5,
        body: [
          'Nominal interest rate is the rate actually paid. Real interest rate ≈ nominal rate − inflation rate.',
          'Borrowers and lenders care about real rates: the real rate is the actual cost of borrowing or the actual reward for saving.',
          'In a 2% inflation environment, a 5% nominal mortgage has a real rate of about 3%.',
        ],
        formula: 'Real interest rate ≈ Nominal interest rate − Inflation rate',
        diagram: null,
        keyTerms: ['nominal interest rate', 'real interest rate', 'Fisher equation'],
      },
      {
        id: '3.5.6',
        title: 'Effectiveness of monetary policy',
        minutes: 6,
        body: [
          'Strengths: incremental, flexible, easily reversible, short time lags (relative to fiscal).',
          'Constraints: limited scope when rates are near zero (the zero lower bound); low consumer/business confidence can blunt the response; global capital flows can offset domestic rate moves.',
          'Most effective in closing demand-deficient (recessionary) gaps; less effective against supply-side shocks.',
        ],
        diagram: null,
        keyTerms: ['zero lower bound', 'liquidity trap', 'transmission lag'],
      },
    ],
  },
  {
    id: '3.6',
    code: '3.6',
    title: 'Fiscal policy',
    blurb: 'How governments use taxes and spending to steer the economy.',
    outcomes: [
      'Describe the sources of government revenue and types of expenditure.',
      'Explain the goals and transmission of fiscal policy using AD/AS.',
      '(HL) Calculate the Keynesian multiplier and discuss its determinants.',
      'Evaluate the effectiveness of fiscal policy, including constraints like crowding out.',
    ],
    lessons: [
      {
        id: '3.6.1',
        title: 'Government revenue and expenditure',
        minutes: 6,
        body: [
          'Revenue: direct taxes (income, corporate, wealth), indirect taxes (VAT, excise), sale of goods and services from state-owned enterprises, sale of assets, borrowing.',
          'Expenditure: current (salaries, goods, services, interest payments), capital (infrastructure, equipment), transfer payments (pensions, unemployment benefit, child benefit).',
          'A budget deficit = expenditure > revenue. Government (national) debt is the stock of accumulated past deficits.',
        ],
        diagram: null,
        keyTerms: ['budget deficit', 'budget surplus', 'government debt', 'current expenditure', 'capital expenditure', 'transfer payments'],
      },
      {
        id: '3.6.2',
        title: 'Goals and transmission of fiscal policy',
        minutes: 7,
        body: [
          'Goals: low inflation, low unemployment, stable long-term growth, smoothing the cycle, equitable income distribution, external balance.',
          'Expansionary fiscal policy: increase G, cut T, or both. AD shifts right. Used to close a deflationary/recessionary gap.',
          'Contractionary fiscal policy: cut G, raise T, or both. AD shifts left. Used to close an inflationary gap or reduce debt.',
        ],
        diagram: 'adas',
        keyTerms: ['expansionary fiscal policy', 'contractionary fiscal policy', 'fiscal stance', 'automatic stabiliser'],
      },
      {
        id: '3.6.3',
        title: '(HL) The Keynesian multiplier',
        minutes: 10,
        body: [
          'A change in an injection (G, I, X) has a multiplied effect on national income, because each round of spending becomes someone else\'s income, which they partly re-spend.',
          'The size of the multiplier depends on leakages: marginal propensities to save (MPS), tax (MPT), and import (MPM).',
        ],
        formula: 'Multiplier k = 1 / (MPS + MPT + MPM)',
        bodyAfter: [
          'A $1 billion rise in G with MPS = 0.2, MPT = 0.2, MPM = 0.2 → multiplier = 1/0.6 ≈ 1.67, raising GDP by ~$1.67 billion.',
          'Higher leakages = smaller multiplier. Open economies with high MPM have smaller multipliers than closed economies.',
        ],
        diagram: null,
        keyTerms: ['Keynesian multiplier', 'marginal propensity to consume (MPC)', 'marginal propensity to save (MPS)', 'marginal propensity to import (MPM)', 'marginal propensity to tax (MPT)'],
      },
      {
        id: '3.6.4',
        title: 'Automatic stabilisers and discretionary policy',
        minutes: 6,
        body: [
          'Automatic stabilisers: progressive income tax (revenue falls automatically in a downturn) and unemployment benefits (spending rises automatically). They cushion the cycle without any new government action.',
          'Discretionary policy: deliberate changes to G or T decided by the government (e.g. a stimulus package). Slower — political lags, recognition lags, implementation lags.',
        ],
        diagram: null,
        keyTerms: ['automatic stabiliser', 'discretionary fiscal policy', 'implementation lag', 'recognition lag'],
      },
      {
        id: '3.6.5',
        title: '(HL) Crowding out and effectiveness',
        minutes: 7,
        body: [
          'Crowding out: when expansionary fiscal policy raises interest rates and reduces private investment (I), partially offsetting the boost to AD.',
          'More likely in economies near full employment, with high private-sector credit demand, and where the central bank does not accommodate the fiscal expansion.',
          'Effectiveness constraints: political pressure, time lags, sustainable debt, crowding out (HL).',
          'Strengths: can target specific sectors, effective in deep recession when monetary policy is constrained.',
        ],
        diagram: 'crowdingOut',
        keyTerms: ['crowding out', 'sustainable debt', 'debt servicing'],
      },
    ],
  },
  {
    id: '3.7',
    code: '3.7',
    title: 'Supply-side policies',
    blurb: 'Shifting the whole curve right, not just chasing the gap — long-term growth through productivity.',
    outcomes: [
      'Distinguish market-based and interventionist supply-side policies, with examples.',
      'Explain the demand-side and supply-side effects of supply-side policies.',
      'Evaluate the effectiveness of supply-side policies using appropriate criteria.',
    ],
    lessons: [
      {
        id: '3.7.1',
        title: 'Goals of supply-side policy',
        minutes: 5,
        body: [
          'Supply-side policies aim to increase the economy\'s productive capacity over the long term — they shift LRAS (and, in Keynesian models, the long-run AS curve) to the right.',
          'Other goals: improve competition and efficiency, lower labour costs, reduce inflation, raise incentives to invest.',
        ],
        diagram: 'adas',
        keyTerms: ['supply-side policy', 'LRAS shift', 'productive capacity'],
      },
      {
        id: '3.7.2',
        title: 'Market-based policies',
        minutes: 7,
        body: [
          'Pro-competition: deregulation, privatisation, trade liberalisation, anti-monopoly regulation.',
          'Labour market flexibility: weakening trade unions, reducing unemployment benefits, abolishing minimum wages (often criticised for equity effects).',
          'Incentive policies: cuts to personal income tax, business tax, capital gains tax.',
          'Strengths: improved resource allocation, lower burden on government budget. Weaknesses: equity issues, time lags, environmental impact, vested interests.',
        ],
        diagram: 'adas',
        keyTerms: ['deregulation', 'privatisation', 'trade liberalisation', 'labour market flexibility', 'anti-monopoly regulation'],
      },
      {
        id: '3.7.3',
        title: 'Interventionist policies',
        minutes: 6,
        body: [
          'Human capital: education, training, healthcare (quality, quantity, access).',
          'Infrastructure: transport, energy, digital.',
          'Research and development: grants, tax credits, public research bodies.',
          'Industrial policy: targeted support for specific sectors (e.g. semiconductors, green tech).',
          'Strengths: directly supports sectors important for growth. Weaknesses: cost, time lags, government failure risk (picking winners).',
        ],
        diagram: 'adas',
        keyTerms: ['interventionist supply-side policy', 'industrial policy', 'infrastructure investment', 'human capital', 'R&D'],
      },
      {
        id: '3.7.4',
        title: 'Effectiveness of supply-side policies',
        minutes: 6,
        body: [
          'Evaluate using: time lags, fiscal cost, equity impact, sustainability, political feasibility, and how easy the policy is to reverse.',
          'Market-based policies tend to act faster on incentives but raise equity concerns.',
          'Interventionist policies can be precisely targeted but take longer to flow through to LRAS.',
          'A balanced mix is usually best — relying on only one type has predictable limits.',
        ],
        diagram: null,
        keyTerms: ['government failure', 'picking winners', 'time lag (supply-side)'],
      },
    ],
  },
];
// Glossary — every key term in the IBDP Economics Unit 3 (Macroeconomics) syllabus.
// Deduplicated, alphabetised, and grouped by topic for easy auditing. 374 entries.

export const GLOSSARY = [
  { term: 'Circular flow of income', definition: 'A model showing the flow of money, goods and services between households, firms, government and the foreign sector, with injections and leakages.' },
  { term: 'Households', definition: 'In the circular flow, the sector that owns the factors of production, supplies them to firms, and uses income to buy goods and services.' },
  { term: 'Firms', definition: 'In the circular flow, the sector that uses the factors of production to produce goods and services.' },
  { term: 'Government sector', definition: 'In the circular flow, the sector that collects taxes and provides government spending and transfers.' },
  { term: 'Foreign sector (overseas sector)', definition: 'In the circular flow, the rest-of-the-world sector that buys exports from and sells imports to the domestic economy.' },
  { term: 'Factors of production', definition: 'The resources used to produce goods and services: land, labour, capital and entrepreneurship.' },
  { term: 'Land', definition: 'Natural resources used in production; the payment to land is rent.' },
  { term: 'Labour', definition: 'Human effort (physical and mental) used in production; the payment to labour is wages.' },
  { term: 'Capital', definition: 'Machinery, tools, buildings and technology used in production; the payment to capital is interest.' },
  { term: 'Entrepreneurship', definition: 'The initiative to combine the other factors of production to create goods and services; the payment to entrepreneurship is profit.' },
  { term: 'Rent', definition: 'The payment to landowners for the use of land as a factor of production.' },
  { term: 'Wages', definition: 'The payment to workers for their labour as a factor of production.' },
  { term: 'Interest (factor payment)', definition: 'The payment to capital owners for the use of their capital.' },
  { term: 'Profit (factor payment)', definition: 'The residual payment to entrepreneurs after other factor payments have been made.' },
  { term: 'Income flow', definition: 'The total payments made by firms to households for the use of factors of production.' },
  { term: 'Expenditure flow', definition: 'The total spending by households on goods and services produced by firms.' },
  { term: 'Value of output flow', definition: 'The total monetary value of goods and services produced by firms; equal to income and expenditure flows in equilibrium.' },
  { term: 'Closed economy', definition: 'An economy with no international trade or financial flows — no exports or imports.' },
  { term: 'Open economy', definition: 'An economy that trades goods, services and financial assets with the rest of the world.' },
  { term: 'Injections', definition: 'Additions to the circular flow: investment (I), government spending (G) and exports (X).' },
  { term: 'Leakages (withdrawals)', definition: 'Withdrawals from the circular flow: saving (S), taxes (T) and imports (M).' },
  { term: 'Savings', definition: 'Income not spent on consumption; a leakage from the circular flow.' },
  { term: 'Taxes', definition: 'Compulsory payments to the government; a leakage from the circular flow.' },
  { term: 'Import expenditure', definition: 'Spending by domestic residents on goods and services produced abroad; a leakage.' },
  { term: 'Investment (I)', definition: 'Spending by firms on capital goods (machinery, buildings, infrastructure); an injection.' },
  { term: 'Government expenditure (G)', definition: 'Spending by the government on goods, services, infrastructure and transfers; an injection.' },
  { term: 'Export revenue', definition: 'Income received from selling domestically produced goods and services abroad; an injection.' },
  { term: 'Expenditure approach', definition: 'Method of calculating national income by summing total spending: C + I + G + (X − M).' },
  { term: 'Income approach', definition: 'Method of calculating national income by summing all factor incomes (wages, rent, interest, profit).' },
  { term: 'Output approach', definition: 'Method of calculating national income by summing the value added at each stage of production.' },
  { term: 'GDP (Gross Domestic Product)', definition: 'The market value of all final goods and services produced within a country in a given period.' },
  { term: 'Nominal GDP', definition: 'GDP measured at current market prices; not adjusted for inflation.' },
  { term: 'Real GDP', definition: 'GDP adjusted for changes in the price level using a price deflator; allows comparisons over time.' },
  { term: 'GNI (Gross National Income)', definition: 'GDP plus net primary income from abroad; the total income earned by a country\'s residents.' },
  { term: 'Price deflator (GDP deflator)', definition: 'A price index (base year = 100) used to convert nominal GDP into real GDP; reflects prices of all domestically produced goods.' },
  { term: 'Net primary income', definition: 'Income earned by residents abroad minus income earned by foreigners domestically.' },
  { term: 'Final goods and services', definition: 'Goods and services sold to the final user; intermediate goods are excluded to avoid double-counting.' },
  { term: 'Intermediate goods', definition: 'Goods used as inputs in the production of other goods; excluded from GDP to avoid double-counting.' },
  { term: 'Double counting', definition: 'Counting the value of intermediate goods more than once in GDP; avoided by counting only final goods or by using the value-added method.' },
  { term: 'Value added', definition: 'The value of a firm\'s output minus the value of its intermediate inputs; summing value added across all firms gives GDP.' },
  { term: 'GDP per capita', definition: 'GDP divided by population; the average real GDP per person, used to compare living standards.' },
  { term: 'Real GDP per capita', definition: 'GDP per capita adjusted for inflation; the standard measure of average living standard over time.' },
  { term: 'Real GNI per capita', definition: 'GNI per capita adjusted for inflation.' },
  { term: 'Purchasing power parity (PPP)', definition: 'An exchange-rate adjustment that equalises the purchasing power of different currencies, so the same amount buys the same basket of goods everywhere.' },
  { term: 'GDP per capita at PPP', definition: 'GDP per capita adjusted for purchasing power parity; the standard cross-country welfare comparison.' },
  { term: 'Business cycle', definition: 'Short-term fluctuations in real GDP around a long-term growth trend, with phases of expansion, peak, contraction and trough.' },
  { term: 'Long-run growth trend', definition: 'The smooth upward path of potential output over time; the long-run trend the business cycle fluctuates around.' },
  { term: 'Potential output (Yf)', definition: 'The level of real GDP consistent with the natural rate of unemployment; also called full-employment output.' },
  { term: 'Full-employment output', definition: 'Another term for potential output: the level of real GDP at which unemployment equals its natural rate.' },
  { term: 'Output gap', definition: 'The difference between actual real GDP and potential output. Positive = above potential (inflationary); negative = below potential (recessionary).' },
  { term: 'Recession', definition: 'A significant decline in real GDP for two or more consecutive quarters (common rule of thumb).' },
  { term: 'Expansion', definition: 'A phase of the business cycle in which real GDP is rising.' },
  { term: 'Peak', definition: 'The turning point at which an expansion ends and a contraction begins.' },
  { term: 'Trough', definition: 'The turning point at which a contraction ends and an expansion begins.' },
  { term: 'Contraction', definition: 'A phase of the business cycle in which real GDP is falling.' },
  { term: 'Recessionary gap', definition: 'A negative output gap: short-run equilibrium output is below potential output.' },
  { term: 'Inflationary gap', definition: 'A positive output gap: short-run equilibrium output exceeds potential output.' },
  { term: 'OECD Better Life Index', definition: 'An index measuring well-being across 11 dimensions: housing, income, jobs, community, education, environment, civic engagement, health, life satisfaction, safety and work-life balance.' },
  { term: 'Human Development Index (HDI)', definition: 'A composite index of life expectancy, education (mean and expected years of schooling) and per-capita income.' },
  { term: 'Happy Planet Index', definition: 'An index that weights life satisfaction and life expectancy by ecological footprint, capturing sustainable well-being.' },
  { term: 'Well-being', definition: 'A broader measure of human welfare than GDP; includes health, education, environment, security and quality of life.' },
  { term: 'Standard of living', definition: 'The level of material comfort, goods and necessities available to a person or group, usually measured by real GDP per capita.' },
  { term: 'Quality of life', definition: 'A broader concept than standard of living, including health, environment, education, leisure and life satisfaction.' },
  { term: 'Aggregate demand (AD)', definition: 'The total quantity of real output demanded at each price level; AD = C + I + G + (X − M).' },
  { term: 'AD curve', definition: 'A downward-sloping curve in price–output space showing the quantity of real GDP demanded at each price level.' },
  { term: 'Consumption (C)', definition: 'Spending by households on goods and services; the largest component of AD.' },
  { term: 'Investment (I) (in AD)', definition: 'Spending by firms on capital goods, plus residential construction and changes in inventories; a component of AD.' },
  { term: 'Government spending (G) (in AD)', definition: 'Government expenditure on goods, services and investment; a component of AD. Excludes transfer payments.' },
  { term: 'Net exports (X − M)', definition: 'The value of exports minus the value of imports; a component of AD.' },
  { term: 'Exports (X)', definition: 'Goods and services produced domestically and sold abroad.' },
  { term: 'Imports (M)', definition: 'Goods and services produced abroad and bought by domestic residents.' },
  { term: 'Determinants of AD', definition: 'Factors that shift the AD curve: C depends on confidence, interest rates, wealth, taxes, debt, expectations; I on rates, business confidence, technology, taxes; G on policy; X − M on foreign income, exchange rates, trade policy.' },
  { term: 'Consumer confidence', definition: 'Households\' optimism about the economy; higher confidence raises consumption and shifts AD right.' },
  { term: 'Business confidence', definition: 'Firms\' optimism about future sales and profits; higher confidence raises investment and shifts AD right.' },
  { term: 'Wealth effect', definition: 'The change in consumption caused by a change in household wealth (e.g. house prices, share prices).' },
  { term: 'Real balances effect', definition: 'The component of the AD slope driven by changes in the real value of money holdings as the price level changes.' },
  { term: 'Interest rate effect', definition: 'The component of the AD slope driven by changes in interest rates (and hence investment and interest-sensitive consumption) as the price level changes.' },
  { term: 'International competitiveness effect', definition: 'The component of the AD slope driven by changes in net exports as the price level affects the exchange rate and competitiveness.' },
  { term: 'Short-run aggregate supply (SRAS)', definition: 'The total quantity of real output supplied at each price level in the short run, when some input prices (especially nominal wages) are sticky.' },
  { term: 'SRAS curve', definition: 'A curve in price–output space that slopes upward in the short run and becomes vertical at potential output.' },
  { term: 'Sticky wages', definition: 'The observation that nominal wages adjust slowly to changes in economic conditions, producing a positively-sloped SRAS.' },
  { term: 'Sticky prices', definition: 'The observation that many prices adjust slowly to changes in supply or demand, especially in the short run.' },
  { term: 'Costs of factors of production', definition: 'Wages, rents, interest and other input costs that affect firms\' production costs and shift the SRAS curve.' },
  { term: 'Indirect taxes (in SRAS)', definition: 'Taxes on spending (e.g. VAT) or production; an increase in indirect taxes shifts SRAS left.' },
  { term: 'Cost-push shock', definition: 'An increase in production costs (e.g. oil price) that shifts SRAS left, raising prices and lowering output.' },
  { term: 'Favourable supply shock', definition: 'A decrease in production costs or an increase in productivity that shifts SRAS right, lowering prices and raising output.' },
  { term: 'Adverse supply shock', definition: 'An increase in costs that shifts SRAS left; a cost-push shock.' },
  { term: 'Long-run aggregate supply (LRAS)', definition: 'A vertical curve at potential output (in the monetarist model), representing the economy\'s productive capacity independent of the price level.' },
  { term: 'LRAS curve', definition: 'The long-run aggregate supply curve; vertical at potential output in the monetarist/new classical view.' },
  { term: 'Monetarist / new classical view', definition: 'A school of macroeconomic thought emphasising money supply, with LRAS vertical at the natural rate; the economy self-corrects to potential output in the long run.' },
  { term: 'Monetarist', definition: 'A school of thought emphasising the role of money supply and expecting the economy to self-correct to potential output in the long run.' },
  { term: 'New classical', definition: 'A school combining monetarist long-run neutrality with rational expectations; LRAS is vertical at the natural rate.' },
  { term: 'Keynesian view', definition: 'A school of thought arguing that prices and wages are sticky, so the economy can remain below potential for extended periods without policy intervention.' },
  { term: 'Keynesian AS curve', definition: 'A long-run aggregate supply curve that continues to slope upward because wages and prices adjust slowly.' },
  { term: 'Vertical LRAS', definition: 'A graphical representation of the monetarist view that long-run output is independent of the price level.' },
  { term: 'Macroeconomic equilibrium', definition: 'A state where aggregate output demanded equals aggregate output supplied; in the short run at AD = SRAS, in the long run at AD = LRAS = SRAS at Yf.' },
  { term: 'Short-run equilibrium', definition: 'The intersection of AD and SRAS, giving the current real output and price level.' },
  { term: 'Long-run equilibrium', definition: 'A state where output equals potential (Y = Yf) with the price level determined by the AD curve at Yf.' },
  { term: 'Equilibrium in the monetarist model', definition: 'The state in which AD = LRAS = SRAS at potential output; the economy self-corrects to this point.' },
  { term: 'Equilibrium in the Keynesian model', definition: 'A state where AD = SRAS, which may be below potential output if AD is weak; persistent deflationary gaps are possible.' },
  { term: 'Self-correction', definition: 'The mechanism (in monetarist models) by which the economy returns to potential output through wage and price adjustment.' },
  { term: 'Automatic adjustment to full employment', definition: 'The monetarist claim that the economy will return to full employment on its own without active policy.' },
  { term: 'Persistence of deflationary gaps (Keynesian)', definition: 'The Keynesian view that the economy can remain below potential output for extended periods without automatic correction.' },
  { term: 'Assumptions of the monetarist model', definition: 'Flexible wages and prices, rational agents, no money illusion; leads to vertical LRAS and self-correction.' },
  { term: 'Assumptions of the Keynesian model', definition: 'Sticky wages and prices, especially in the short run; allows persistent output gaps and a role for active policy.' },
  { term: 'Economic growth', definition: 'An increase in the productive capacity of the economy (long-run growth) or actual real GDP (short-run growth).' },
  { term: 'Actual growth (in the PPC model)', definition: 'Movement of the economy to a point on a higher PPC curve, showing the economy producing more of all goods.' },
  { term: 'Short-term growth', definition: 'Growth driven by an outward shift of AD, raising actual real GDP and possibly the price level.' },
  { term: 'Long-term growth', definition: 'Growth driven by an outward shift of LRAS, raising potential output.' },
  { term: 'Production possibilities curve (PPC)', definition: 'A graph showing the maximum combinations of two goods an economy can produce with its available resources and technology.' },
  { term: 'PPC shift', definition: 'A rightward shift of the PPC, representing growth in production possibilities from more or better resources or technology.' },
  { term: 'LRAS shift', definition: 'A rightward shift of LRAS caused by more or better factors of production, technological progress, or improved efficiency.' },
  { term: 'Rate of economic growth', definition: 'The annual percentage change in real GDP, usually calculated over one year.' },
  { term: 'Unemployment', definition: 'A situation in which people of working age who are willing and able to work cannot find a job.' },
  { term: 'Unemployment rate', definition: 'The number of unemployed people divided by the labour force, expressed as a percentage.' },
  { term: 'Labour force', definition: 'The sum of employed and unemployed people who are actively seeking work; excludes those not seeking work.' },
  { term: 'Labour force participation rate', definition: 'The labour force as a percentage of the working-age population.' },
  { term: 'Employed', definition: 'A person aged 15+ who worked for pay or profit, or had a job but was temporarily absent, in the reference week.' },
  { term: 'Unemployed', definition: 'A person aged 15+ who was without work, available to start work in the reference week, and had actively sought work in the previous four weeks.' },
  { term: 'Discouraged worker', definition: 'A person who would work if a job were available but has stopped actively seeking work; not counted in the unemployment rate.' },
  { term: 'Cyclical unemployment (demand-deficient unemployment)', definition: 'Unemployment caused by a downturn in AD; rises during recessions and falls during expansions.' },
  { term: 'Demand-deficient unemployment', definition: 'Another name for cyclical unemployment: unemployment caused by insufficient aggregate demand.' },
  { term: 'Structural unemployment', definition: 'Unemployment caused by a mismatch between workers\' skills (or locations) and the skills (or locations) demanded by employers.' },
  { term: 'Seasonal unemployment', definition: 'Unemployment caused by predictable changes in demand across the year (e.g. tourism, agriculture).' },
  { term: 'Frictional unemployment', definition: 'Short-run unemployment while workers transition between jobs or enter the labour force for the first time.' },
  { term: 'Natural rate of unemployment', definition: 'The unemployment rate consistent with potential output, equal to the sum of structural, frictional and seasonal unemployment.' },
  { term: 'Full employment', definition: 'A situation in which unemployment equals the natural rate; output equals potential output (Y = Yf).' },
  { term: 'Personal costs of unemployment', definition: 'Lost income, loss of skills, lower self-esteem, poorer health.' },
  { term: 'Social costs of unemployment', definition: 'Higher inequality, social exclusion, increased crime, lower social cohesion.' },
  { term: 'Economic costs of unemployment', definition: 'Lost output (the output gap), lower tax revenue, higher transfer payments; persistent unemployment lowers potential output.' },
  { term: 'Okun\'s law', definition: 'An empirical relationship that for every 1% the unemployment rate is above the natural rate, real GDP is about 2% below potential output.' },
  { term: 'Inflation', definition: 'A sustained increase in the general price level, usually measured by the CPI or another price index.' },
  { term: 'Consumer Price Index (CPI)', definition: 'A weighted average of the prices of a basket of consumer goods and services, used to track the cost of living and inflation.' },
  { term: 'CPI basket', definition: 'The representative set of goods and services whose prices are tracked in the CPI; weighted by expenditure share.' },
  { term: 'Weighted price index (HL)', definition: 'A price index where each item is weighted by its share in total expenditure (e.g. CPI weights).' },
  { term: 'Inflation rate', definition: 'The annual percentage change in a price index (usually CPI).' },
  { term: 'Core inflation', definition: 'Inflation measured excluding volatile items like food and energy; seen as a better indicator of underlying inflation.' },
  { term: 'Headline inflation', definition: 'Inflation as measured by the overall CPI, including volatile items like food and energy.' },
  { term: 'Limitations of the CPI', definition: 'Quality change, new products, substitution bias, different spending patterns across households, outdated basket.' },
  { term: 'Substitution bias', definition: 'The CPI tends to overstate inflation because it does not fully account for consumers substituting away from goods whose prices have risen the most.' },
  { term: 'Demand-pull inflation', definition: 'Inflation caused by AD rising faster than AS, often associated with growth above potential.' },
  { term: 'Cost-push inflation', definition: 'Inflation caused by a leftward shift of SRAS (e.g. higher oil prices), with output falling — stagflation.' },
  { term: 'Stagflation', definition: 'A combination of stagnant or falling output and rising prices, typically caused by an adverse supply shock.' },
  { term: 'Costs of high inflation', definition: 'Uncertainty, redistributive effects, reduced saving, damage to export competitiveness, slower growth, inefficient resource allocation.' },
  { term: 'Menu costs', definition: 'The real costs to firms of changing prices frequently (printing new menus, updating systems); a reason for sticky prices.' },
  { term: 'Shoe-leather costs', definition: 'The real costs of inflation from making more frequent trips to the bank to withdraw cash as its real value falls.' },
  { term: 'Redistributive effects of inflation', definition: 'Inflation redistributes wealth from creditors to debtors and from those on fixed incomes to those with flexible incomes.' },
  { term: 'Deflation', definition: 'A sustained decrease in the general price level.' },
  { term: 'Disinflation', definition: 'A decrease in the inflation rate (the rate at which prices are rising slows down).' },
  { term: 'Costs of deflation', definition: 'Uncertainty, redistributive effects (debtors lose), deferred consumption, high cyclical unemployment and bankruptcies, increased real value of debt, policy ineffectiveness at the zero lower bound.' },
  { term: 'Debt-deflation spiral', definition: 'A situation in which falling prices raise the real value of debt, leading to defaults, lower spending, further price falls, and so on.' },
  { term: 'Government (national) debt', definition: 'The stock of debt owed by the central government; usually measured as a percentage of GDP.' },
  { term: 'Government debt as % of GDP', definition: 'The ratio of government debt to annual GDP; a common measure of debt sustainability.' },
  { term: 'Relationship between deficit and debt', definition: 'A budget deficit adds to government debt; a surplus reduces it. Debt is the stock, deficit/surplus is the flow.' },
  { term: 'Credit rating', definition: 'An assessment of a borrower\'s (e.g. government\'s) ability to repay debt; lower ratings mean higher borrowing costs.' },
  { term: 'Debt servicing', definition: 'The interest payments the government makes on its outstanding debt.' },
  { term: 'Sustainable debt', definition: 'A level of government debt that can be serviced without forcing disruptive adjustments to fiscal policy.' },
  { term: 'Phillips curve', definition: 'A curve showing the relationship between the inflation rate and the unemployment rate.' },
  { term: 'Short-run Phillips curve (SRPC)', definition: 'A downward-sloping curve showing the inverse short-run relationship between inflation and unemployment.' },
  { term: 'Long-run Phillips curve (LRPC)', definition: 'A vertical curve at the natural rate of unemployment, reflecting the long-run neutrality of inflation.' },
  { term: 'Expectations-augmented Phillips curve', definition: 'A version of the Phillips curve in which the SRPC shifts when expected inflation changes.' },
  { term: 'Natural rate hypothesis', definition: 'The proposition that in the long run the economy returns to the natural rate of unemployment regardless of the inflation rate.' },
  { term: 'Phillips curve trade-off (HL)', definition: 'The short-run inverse relationship between inflation and unemployment; no permanent trade-off in the long run.' },
  { term: 'Trade-off', definition: 'A situation in which improving one objective (e.g. lower inflation) requires worsening another (e.g. higher unemployment in the short run).' },
  { term: 'Sustainability (of growth)', definition: 'Growth that can be maintained over time without depleting natural, human or social capital.' },
  { term: 'Environmental sustainability', definition: 'Economic activity that does not deplete natural resources or damage ecosystems beyond their capacity to recover.' },
  { term: 'Equity (in income distribution)', definition: 'Fairness in the distribution of income, wealth or opportunity; often in tension with growth and efficiency.' },
  { term: 'Income distribution', definition: 'How total national income is divided among households or individuals.' },
  { term: 'Wealth distribution', definition: 'How total wealth is divided among households or individuals.' },
  { term: 'Equality', definition: 'Treating everyone the same; the same resources, opportunities or outcomes for all.' },
  { term: 'Equity', definition: 'Fairness in the distribution of resources, opportunities or outcomes; distinct from equality.' },
  { term: 'Income inequality', definition: 'The unequal distribution of current income across households or individuals.' },
  { term: 'Wealth inequality', definition: 'The unequal distribution of asset ownership across households or individuals.' },
  { term: 'Lorenz curve', definition: 'A graph plotting cumulative share of income (y-axis) against cumulative share of population (x-axis); the further it bows from the 45° line, the more unequal the distribution.' },
  { term: 'Line of perfect equality', definition: 'The 45° line on a Lorenz diagram representing a perfectly equal distribution of income.' },
  { term: 'Line of perfect inequality', definition: 'The line at 0% income for 99% of the population and 100% income for the top 1%.' },
  { term: 'Gini coefficient (Gini index)', definition: 'A number between 0 and 1 measuring inequality; 0 = perfect equality, 1 = perfect inequality. Calculated from the Lorenz curve.' },
  { term: 'Absolute poverty', definition: 'Inability to afford a minimum standard of living; often defined relative to an international poverty line (e.g. $2.15/day at PPP).' },
  { term: 'Relative poverty', definition: 'Income below a threshold defined relative to a country\'s typical income (e.g. below 60% of median income).' },
  { term: 'International poverty line', definition: 'A monetary threshold (set by the World Bank) below which a person is considered to be in extreme poverty, expressed at PPP.' },
  { term: 'Single indicators of poverty', definition: 'Measures based on a single dimension, e.g. the international poverty line based on income.' },
  { term: 'Composite indicators of poverty', definition: 'Multi-dimensional measures such as the MPI, combining health, education and living standards.' },
  { term: 'Multidimensional Poverty Index (MPI)', definition: 'A composite measure of poverty across health, education and living standards.' },
  { term: 'Minimum income standards', definition: 'A poverty line based on the cost of a basket of goods and services considered necessary for a basic standard of living.' },
  { term: 'Causes of economic inequality', definition: 'Inequality of opportunity, unequal resource ownership, different human capital, discrimination, tax/benefit policy, globalisation, technology.' },
  { term: 'Causes of poverty', definition: 'Similar to inequality causes, plus absolute factors like lack of access to basic services, weak institutions, conflict.' },
  { term: 'Inequality of opportunity', definition: 'Inequality arising from factors outside an individual\'s control (family background, birthplace, gender, race).' },
  { term: 'Discrimination', definition: 'Unequal treatment of individuals or groups based on characteristics like gender, race, religion, age or disability.' },
  { term: 'Globalisation', definition: 'The increasing integration of national economies through trade, investment, migration and the spread of technology.' },
  { term: 'Skill-biased technical change', definition: 'Technological progress that raises the demand for skilled workers relative to unskilled workers, widening wage inequality.' },
  { term: 'Tax and benefits policies (inequality)', definition: 'Government policies that redistribute income through taxation and transfer payments, affecting inequality.' },
  { term: 'Impact of inequality on growth', definition: 'High inequality can reduce growth through weaker human capital, lower aggregate demand, and political instability.' },
  { term: 'Impact of inequality on living standards', definition: 'Inequality reduces the living standards of the worst-off, even if average income rises.' },
  { term: 'Impact of inequality on social stability', definition: 'High inequality can erode trust, fuel political polarisation and increase social tensions.' },
  { term: 'Progressive tax', definition: 'A tax whose average rate rises with the taxpayer\'s income.' },
  { term: 'Regressive tax', definition: 'A tax whose average rate falls as income rises (typical of indirect taxes on consumption).' },
  { term: 'Proportional tax', definition: 'A tax whose rate is the same for all taxpayers, regardless of income.' },
  { term: 'Average tax rate', definition: 'Total tax paid divided by total income.' },
  { term: 'Marginal tax rate', definition: 'The tax rate applied to the next unit of income; affects behaviour more than the average rate.' },
  { term: 'Direct tax', definition: 'A tax levied directly on income or wealth (e.g. income tax, corporate tax, wealth tax).' },
  { term: 'Indirect tax', definition: 'A tax levied on spending (e.g. VAT, excise duty), usually regressive.' },
  { term: 'Personal income tax', definition: 'A direct tax on individuals\' income; can be progressive, proportional or regressive depending on structure.' },
  { term: 'Corporate income tax', definition: 'A direct tax on company profits.' },
  { term: 'Wealth tax', definition: 'A direct tax on the value of assets owned; a progressive tax on net worth.' },
  { term: 'Value-added tax (VAT)', definition: 'A tax on the value added at each stage of production; a common indirect tax.' },
  { term: 'Excise duty', definition: 'A tax on specific goods such as alcohol, tobacco or fuel; usually regressive.' },
  { term: 'Progressive taxation (role)', definition: 'Reduces inequality by taxing higher incomes at higher average rates; can fund transfers and public services.' },
  { term: 'Indirect tax burden (HL)', definition: 'Given an indirect tax rate, the amount of tax paid from a given level of expenditure.' },
  { term: 'Policies to reduce inequality of opportunity', definition: 'Public investment in education, healthcare, early childhood programs, and anti-discrimination law.' },
  { term: 'Transfer payments', definition: 'Government payments to individuals for which no good or service is received in return (e.g. pensions, unemployment benefit, child benefit).' },
  { term: 'Targeted spending', definition: 'Government spending on specific goods or services for groups in need (e.g. food stamps, housing assistance).' },
  { term: 'Universal basic income (UBI)', definition: 'A regular cash payment from the government to every adult, regardless of income or employment status.' },
  { term: 'Means-tested', definition: 'A benefit or service available only to those whose income or assets fall below a defined threshold.' },
  { term: 'Minimum wage', definition: 'A legal floor on the hourly wage rate; can raise the wage of low-paid workers but may also reduce employment if set above the equilibrium.' },
  { term: 'Investment in human capital', definition: 'Spending on education, training and healthcare that raises the skills and productivity of workers.' },
  { term: 'Human capital', definition: 'The skills, knowledge, health and experience embodied in workers, which raise their productivity.' },
  { term: 'Social mobility', definition: 'The degree to which individuals move up or down the income distribution over their lifetime or across generations.' },
  { term: 'Intergenerational mobility', definition: 'The extent to which children\'s economic status differs from their parents\'.' },
  { term: 'Income redistribution', definition: 'Government policies (taxes and transfers) that reduce inequality by transferring income from higher- to lower-income households.' },
  { term: 'Monetary policy', definition: 'Policy set by the central bank, typically adjusting short-term interest rates, to influence macroeconomic outcomes.' },
  { term: 'Central bank', definition: 'A public institution that issues currency, manages the money supply and sets the policy rate (e.g. the Federal Reserve, ECB, Bank of England).' },
  { term: 'Money supply', definition: 'The total stock of money in circulation in an economy; usually defined as M1 (currency + demand deposits) or broader measures.' },
  { term: 'Interest rates (in monetary policy)', definition: 'The cost of borrowing money; central banks set a short-term policy rate that influences the whole rate structure.' },
  { term: 'Inflation targeting', definition: 'A monetary policy framework in which the central bank announces an explicit inflation target and adjusts the policy rate to hit it.' },
  { term: 'Monetary policy goals', definition: 'Low and stable inflation, low unemployment, smoothing the business cycle, supporting long-term growth, external balance.' },
  { term: 'Policy rate', definition: 'The short-term interest rate set by the central bank, which anchors the structure of market interest rates.' },
  { term: 'Base rate', definition: 'The interest rate at which the central bank lends to commercial banks; synonymous with policy rate / discount rate / refinancing rate (in different jurisdictions).' },
  { term: 'Discount rate', definition: 'The rate at which the central bank lends directly to commercial banks; lowering it is expansionary.' },
  { term: 'Refinancing rate', definition: 'The rate at which the central bank lends to commercial banks against eligible collateral; the main policy rate in the eurozone.' },
  { term: 'Commercial banks', definition: 'Privately-owned banks that accept deposits, make loans and create money in the process.' },
  { term: 'Money creation (HL)', definition: 'The process by which commercial banks create new deposits when they make loans, expanding the money supply.' },
  { term: 'Reserve', definition: 'Cash or deposits that commercial banks hold at the central bank, used to settle interbank payments and meet reserve requirements.' },
  { term: 'Reserve ratio', definition: 'The fraction of customer deposits that a commercial bank must hold as reserves.' },
  { term: 'Money multiplier (HL)', definition: 'The ratio of new deposits created to new reserves; equal to 1 ÷ reserve ratio in the simplest model.' },
  { term: 'Fractional reserve banking', definition: 'A banking system in which banks hold only a fraction of deposits as reserves and lend the rest.' },
  { term: 'Tools of monetary policy (HL)', definition: 'Open market operations, minimum reserve requirements, changes to the central bank minimum lending rate, and quantitative easing.' },
  { term: 'Open market operations', definition: 'The central bank\'s buying or selling of government bonds to change the money supply and the policy rate.' },
  { term: 'Minimum reserve requirements (HL)', definition: 'Regulations requiring banks to hold a minimum fraction of deposits as reserves; raising the ratio is contractionary, lowering it expansionary.' },
  { term: 'Quantitative easing (QE) (HL)', definition: 'Large-scale asset purchases by the central bank, used when the policy rate is near its zero lower bound, to lower long-term yields.' },
  { term: 'Asset purchases (QE)', definition: 'The central bank buying financial assets (typically government bonds) to lower long-term interest rates and inject reserves.' },
  { term: 'Demand for money (HL)', definition: 'The total quantity of money households and firms wish to hold; slopes downward with the nominal interest rate.' },
  { term: 'Supply of money (HL)', definition: 'The total quantity of money issued by the central bank; under normal conditions, set independently of the interest rate.' },
  { term: 'Equilibrium interest rate (HL)', definition: 'The interest rate at which the quantity of money demanded equals the quantity supplied.' },
  { term: 'Money demand curve', definition: 'A downward-sloping curve in interest-rate / quantity-of-money space, showing how much money people want to hold at each rate.' },
  { term: 'Money supply curve', definition: 'A vertical line in interest-rate / quantity-of-money space, set by the central bank.' },
  { term: 'Real interest rate', definition: 'The interest rate adjusted for inflation; approximately equal to the nominal rate minus the inflation rate.' },
  { term: 'Nominal interest rate', definition: 'The interest rate expressed in current money terms, with no adjustment for inflation.' },
  { term: 'Fisher equation', definition: 'The relationship r ≈ i − π, linking real, nominal and inflation rates.' },
  { term: 'Inflation premium', definition: 'The component of the nominal interest rate that compensates lenders for expected inflation.' },
  { term: 'Expansionary monetary policy', definition: 'Policy that lowers interest rates or expands the money supply to raise AD.' },
  { term: 'Contractionary monetary policy', definition: 'Policy that raises interest rates or contracts the money supply to lower AD.' },
  { term: 'Monetary transmission mechanism', definition: 'The chain of effects through which a change in the policy rate affects aggregate demand and the economy.' },
  { term: 'Interest rate channel', definition: 'The part of the monetary transmission mechanism that runs from the policy rate to investment, durable consumption and housing demand.' },
  { term: 'Exchange rate channel', definition: 'The part of the monetary transmission mechanism that runs from the policy rate to the exchange rate and hence to net exports.' },
  { term: 'Asset price channel', definition: 'A part of the monetary transmission mechanism running from the policy rate to asset prices (shares, housing) and hence to wealth and spending.' },
  { term: 'Credit channel', definition: 'A part of the monetary transmission mechanism running from the policy rate to bank lending and credit availability.' },
  { term: 'Effectiveness of monetary policy', definition: 'How well monetary policy achieves its goals; depends on transmission lags, confidence, the zero lower bound, and openness.' },
  { term: 'Strengths of monetary policy', definition: 'Incremental, flexible, easily reversible, and has relatively short time lags.' },
  { term: 'Constraints on monetary policy', definition: 'Limited scope when rates are near zero (the zero lower bound) and low consumer/business confidence that can blunt the response.' },
  { term: 'Zero lower bound', definition: 'The constraint that nominal interest rates cannot fall much below zero, limiting conventional monetary policy.' },
  { term: 'Liquidity trap', definition: 'A situation in which conventional monetary policy is ineffective because interest rates are at or near the zero lower bound.' },
  { term: 'Transmission lag (monetary policy)', definition: 'The delay between a monetary policy action and its effect on the real economy.' },
  { term: 'Unconventional monetary policy', definition: 'Policy tools used when the policy rate is at the zero lower bound, including quantitative easing, forward guidance and negative interest rates.' },
  { term: 'Forward guidance', definition: 'A central bank communication about the future path of the policy rate, intended to shape expectations and lower long-term rates.' },
  { term: 'Negative interest rates', definition: 'A policy rate below zero, used by some central banks at the zero lower bound; charges banks for holding reserves.' },
  { term: 'Effectiveness in promoting growth (monetary)', definition: 'Monetary policy can support growth mainly in demand-deficient recessions, less so against supply shocks or when rates are constrained.' },
  { term: 'Fiscal policy', definition: 'Government policy on taxation and spending to influence aggregate demand and the economy.' },
  { term: 'Sources of government revenue', definition: 'Direct and indirect taxation, sale of goods and services from state-owned enterprises, sale of government assets, and borrowing.' },
  { term: 'Direct taxation (as revenue source)', definition: 'Taxes on income or wealth, e.g. income tax, corporate tax, wealth tax.' },
  { term: 'Indirect taxation (as revenue source)', definition: 'Taxes on spending, e.g. VAT, excise duties.' },
  { term: 'Sale of goods and services from state-owned enterprises', definition: 'A source of government revenue when state-owned firms sell products or services.' },
  { term: 'Sale of government assets', definition: 'Privatisation revenue: the government sells state-owned assets to private owners.' },
  { term: 'Government expenditures', definition: 'Spending by the government on goods, services, infrastructure and transfer payments.' },
  { term: 'Current expenditure', definition: 'Government spending on goods, services and wages consumed within the year.' },
  { term: 'Capital expenditure', definition: 'Government spending on assets that provide value over multiple years (infrastructure, equipment, buildings).' },
  { term: 'Fiscal policy goals', definition: 'Low inflation, low unemployment, stable long-term growth, smoothing the cycle, equitable distribution of income, external balance.' },
  { term: 'Expansionary fiscal policy', definition: 'Policy that increases aggregate demand by raising government spending or cutting taxes.' },
  { term: 'Contractionary fiscal policy', definition: 'Policy that reduces aggregate demand by cutting government spending or raising taxes.' },
  { term: 'Fiscal stance', definition: 'The overall direction of fiscal policy: expansionary, contractionary or neutral.' },
  { term: 'Budget deficit', definition: 'Annual government expenditure exceeding annual revenue.' },
  { term: 'Budget surplus', definition: 'Annual government revenue exceeding annual expenditure.' },
  { term: 'Balanced budget', definition: 'Annual government revenue equal to annual expenditure.' },
  { term: 'Cyclically adjusted budget balance', definition: 'The budget balance adjusted for the state of the business cycle; what the deficit/surplus would be at potential output.' },
  { term: 'Structural deficit', definition: 'The deficit that would exist at potential output, after adjusting for the business cycle.' },
  { term: 'Keynesian multiplier (HL)', definition: 'The ratio of a change in national income to the initial change in autonomous spending that caused it; equal to 1 / (MPS + MPT + MPM).' },
  { term: 'Autonomous spending', definition: 'Spending that does not depend on current income (e.g. investment, government spending, exports).' },
  { term: 'Induced spending', definition: 'Spending that depends on current income (mostly consumption).' },
  { term: 'Marginal propensity to consume (MPC)', definition: 'The fraction of an extra unit of income that households spend on consumption.' },
  { term: 'Marginal propensity to save (MPS)', definition: 'The fraction of an extra unit of income that households save. In a simple closed economy without taxes, MPS = 1 − MPC.' },
  { term: 'Marginal propensity to tax (MPT)', definition: 'The fraction of an extra unit of income that is collected in tax.' },
  { term: 'Marginal propensity to import (MPM)', definition: 'The fraction of an extra unit of income that households spend on imports.' },
  { term: 'Multiplier effect', definition: 'The magnified effect on national income of an initial change in autonomous spending, via successive rounds of consumption.' },
  { term: 'Leakages in the multiplier', definition: 'MPS, MPT and MPM are leakages from the circular flow that reduce the size of the multiplier.' },
  { term: 'Open economy multiplier', definition: 'The multiplier in an open economy: k = 1 / (MPS + MPT + MPM); smaller than the closed-economy multiplier.' },
  { term: 'Closed economy multiplier', definition: 'The multiplier in a closed economy without taxes: k = 1 / (1 − MPC) = 1 / MPS.' },
  { term: 'Balanced budget multiplier', definition: 'The multiplier on an equal increase in G and T; in a simple model equals 1.' },
  { term: 'Effectiveness of fiscal policy', definition: 'How well fiscal policy achieves its goals; depends on time lags, political pressure, debt sustainability, crowding out, and the state of the economy.' },
  { term: 'Constraints on fiscal policy', definition: 'Political pressure, time lags, sustainable debt, and (HL) crowding out.' },
  { term: 'Political pressure (fiscal)', definition: 'Electoral and lobbying pressures that can lead to sub-optimal fiscal decisions (e.g. short-term stimulus, unsustainable tax cuts).' },
  { term: 'Time lags (fiscal)', definition: 'Recognition, decision and implementation lags that delay the effect of fiscal policy on the economy.' },
  { term: 'Crowding out (HL)', definition: 'A reduction in private-sector spending (usually investment) caused by an expansionary fiscal policy raising interest rates.' },
  { term: 'Crowding in', definition: 'An increase in private-sector spending triggered by fiscal policy (e.g. infrastructure that raises productivity).' },
  { term: 'Strengths of fiscal policy', definition: 'Can target specific sectors, is effective in deep recession when monetary policy is constrained, and can address inequality.' },
  { term: 'Automatic stabilisers (HL)', definition: 'Features of the tax-and-transfer system that automatically dampen the business cycle without new government action (e.g. progressive income tax, unemployment benefits).' },
  { term: 'Progressive income tax (as stabiliser)', definition: 'In a downturn, incomes fall and tax revenue falls automatically; the deficit rises and provides fiscal stimulus without new legislation.' },
  { term: 'Unemployment benefits (as stabiliser)', definition: 'Spending on unemployment benefits rises automatically in a downturn, providing income to those who lost jobs and supporting consumption.' },
  { term: 'Strengths and limitations in promoting growth (fiscal)', definition: 'Fiscal policy can support growth via investment and transfers, but is limited by political pressure, time lags and crowding out.' },
  { term: 'Supply-side policy', definition: 'Policy aimed at raising the economy\'s long-term productive capacity (shifting LRAS rightward).' },
  { term: 'Productive capacity', definition: 'The maximum sustainable level of real output the economy can produce.' },
  { term: 'Goals of supply-side policies', definition: 'Long-term growth by raising productive capacity, improving competition and efficiency, reducing labour costs, reducing inflation, raising investment incentives.' },
  { term: 'Market-based supply-side policies', definition: 'Policies that improve resource allocation through market incentives: deregulation, privatisation, trade liberalisation, anti-monopoly regulation, tax cuts, labour market flexibility.' },
  { term: 'Deregulation', definition: 'Removing or simplifying government regulations, typically to encourage competition and reduce costs.' },
  { term: 'Privatisation', definition: 'The transfer of state-owned enterprises to private ownership.' },
  { term: 'Trade liberalisation', definition: 'The reduction of barriers to international trade (tariffs, quotas), typically expansionary for AD and SRAS.' },
  { term: 'Anti-monopoly regulation', definition: 'Rules preventing firms from abusing market power, intended to keep markets competitive.' },
  { term: 'Labour market flexibility', definition: 'Policies that make it easier to hire and fire workers, often by weakening unions or cutting unemployment benefits.' },
  { term: 'Labour unions', definition: 'Organisations representing workers in collective bargaining with employers; strong unions can push wages above the market-clearing level.' },
  { term: 'Incentive-related supply-side policies', definition: 'Tax cuts designed to raise work, saving and investment incentives, e.g. personal income tax cuts, business tax cuts, capital gains tax cuts.' },
  { term: 'Personal income tax cuts', definition: 'Reductions in the tax rate on individual income; aimed at raising work and saving incentives.' },
  { term: 'Business tax cuts', definition: 'Reductions in corporate tax rates; aimed at raising investment incentives.' },
  { term: 'Capital gains tax cuts', definition: 'Reductions in the tax on gains from selling assets like shares; aimed at raising investment and risk-taking.' },
  { term: 'Interventionist supply-side policies', definition: 'Policies in which the government directly invests in human capital, infrastructure, R&D or specific industries to raise long-run productivity.' },
  { term: 'Education and training', definition: 'Government spending on schools, universities and vocational training to raise the stock of human capital.' },
  { term: 'Health care investment', definition: 'Government spending on health services to raise the health and productivity of the workforce.' },
  { term: 'Research and development (R&D)', definition: 'Investment in creating new products, processes and knowledge; often publicly funded because of positive externalities.' },
  { term: 'Infrastructure (public)', definition: 'Public capital such as roads, railways, ports, energy grids and digital networks that raise economy-wide productivity.' },
  { term: 'Industrial policy', definition: 'Targeted government support for specific industries considered important for long-term growth (e.g. semiconductors, green tech).' },
  { term: 'Demand-side effects of supply-side policies', definition: 'Some supply-side policies (e.g. tax cuts) also raise AD, blurring the line between supply-side and demand-side effects.' },
  { term: 'Supply-side effects of fiscal policies', definition: 'Some fiscal policies (e.g. infrastructure spending, R&D tax credits) have supply-side effects by raising long-run productivity.' },
  { term: 'Effectiveness of supply-side policies', definition: 'How well supply-side policies achieve their goals; depends on time lags, fiscal cost, equity impact, political feasibility.' },
  { term: 'Constraints on supply-side policies (market-based)', definition: 'Equity issues (cuts to safety nets hit the poor), time lags, vested interests, environmental impact.' },
  { term: 'Constraints on supply-side policies (interventionist)', definition: 'High fiscal cost, time lags, government failure risk (picking winners).' },
  { term: 'Vested interests', definition: 'Groups that benefit from the status quo and resist reforms that would reduce their privileges; a constraint on supply-side policy.' },
  { term: 'Environmental impact (supply-side)', definition: 'Some supply-side policies (e.g. deregulation, market-based reforms) can worsen environmental outcomes.' },
  { term: 'Strengths of market-based supply-side policies', definition: 'Improved resource allocation, lower burden on government budget, harness market incentives.' },
  { term: 'Strengths of interventionist supply-side policies', definition: 'Direct support of sectors important for growth, can target externalities and public goods.' },
  { term: 'Government failure', definition: 'A situation in which government intervention makes outcomes worse than the market alone would have produced.' },
  { term: 'Picking winners', definition: 'Criticism of industrial policy: that governments lack the information to identify which firms or industries will succeed.' },
  { term: 'Time lag (supply-side)', definition: 'The delay between introducing a supply-side policy and seeing its effect on LRAS and output.' },
  { term: 'Effectiveness in promoting growth (supply-side)', definition: 'Supply-side policies can support long-term growth by raising productive capacity, but their effect is gradual and uncertain.' },
  { term: 'Externalities in supply-side policy', definition: 'Some supply-side investments (e.g. R&D, infrastructure, education) generate positive externalities that the market under-provides, justifying government intervention.' },
  { term: 'Positive externalities (supply-side)', definition: 'Benefits to third parties from supply-side investments (e.g. better-educated workforce benefits society beyond the individual).' },
  { term: 'Ceteris paribus', definition: 'Other things being equal; an assumption that other relevant variables are held constant when analysing the effect of one variable.' },
  { term: 'Short run', definition: 'A period over which some input prices (especially nominal wages) are sticky and cannot fully adjust. In macro, often defined as the time before contracts can be renegotiated.' },
  { term: 'Long run', definition: 'A period long enough for all input prices (including wages) to fully adjust to changes in economic conditions.' },
  { term: 'Nominal vs real', definition: 'Nominal variables are measured in current money; real variables are adjusted for inflation.' },
  { term: 'Stock vs flow', definition: 'A stock is measured at a point in time (e.g. government debt); a flow is measured over a period (e.g. budget deficit).' },
  { term: 'Endogenous variable', definition: 'A variable determined within the model being analysed (e.g. equilibrium output).' },
  { term: 'Exogenous variable', definition: 'A variable determined outside the model (e.g. oil prices, foreign income).' },
  { term: 'Evaluation', definition: 'In IB Economics, weighing the strengths and limitations of a theory or policy, often using criteria like equity, efficiency, sustainability and time lags.' },
  { term: 'Strengths of a policy', definition: 'Reasons why a policy might achieve its goal effectively: low time lag, targeted, sustainable, low cost.' },
  { term: 'Limitations of a policy', definition: 'Reasons why a policy might fail to achieve its goal: high time lag, side effects, equity concerns, fiscal cost, political feasibility.' },
  { term: 'Time lag (policy)', definition: 'The delay between a policy being introduced and it having its intended effect on the economy.' },
  { term: 'Side effects (policy)', definition: 'Unintended or secondary effects of a policy, e.g. higher inflation as a side effect of expansionary policy.' },
  { term: 'Short-term vs long-term effects', definition: 'Many policies have effects that differ between the short run and the long run, sometimes in opposite directions.' },
  { term: 'Diagram conventions', definition: 'Standard IB conventions: AD slopes down, SRAS slopes up, LRAS is vertical; equilibrium shown by a dot; shifts shown by arrows; subscript 0 for original and 1 for new.' },
  { term: 'Real GDP growth rate', definition: 'The annual percentage change in real GDP, calculated as (real GDP this year − real GDP last year) / real GDP last year × 100.' },
  { term: 'National income', definition: 'The total income earned by a country\'s residents in a period; equal to GDP plus net primary income from abroad (GNI).' },
  { term: 'Per capita', definition: 'Per person; per capita measures divide an aggregate by population to enable comparisons.' },
  { term: 'Disposable income (Yd)', definition: 'Income after taxes and transfers; the income households actually have available to spend or save.' },
  { term: 'Marginal rate of taxation', definition: 'The rate of tax applied to the next unit of income; affects incentives at the margin.' },
  { term: 'Average rate of taxation', definition: 'Total tax paid divided by total income; the overall tax burden.' },
  { term: 'Marginal propensity to consume out of disposable income', definition: 'The fraction of an extra unit of disposable income (after tax) that households spend on consumption; the open-economy MPC.' },
  { term: 'Comparative statics', definition: 'Comparing two equilibrium states (before and after a shift) to analyse the effect of a change in an exogenous variable.' },
  { term: 'Adjustment process', definition: 'The path the economy takes from one equilibrium to another, including any time lags and short-run dynamics.' },
  { term: 'Policy effectiveness (general)', definition: 'How well a policy achieves its stated goal; depends on the state of the economy, transmission lags, and side effects.' },
  { term: 'Conflicts between objectives', definition: 'Macroeconomic objectives often conflict (e.g. low inflation vs low unemployment in the short run); policymakers must choose.' },
  { term: 'Trade-off between unemployment and inflation (HL)', definition: 'In the short run, policies that lower unemployment tend to raise inflation, and vice versa; in the long run, no permanent trade-off.' },
  { term: 'High growth vs low inflation', definition: 'Rapid growth may push AD up faster than AS, generating inflation; a possible trade-off.' },
  { term: 'High growth vs environmental sustainability', definition: 'Growth can deplete natural capital; sustainable growth requires balancing economic and environmental goals.' },
  { term: 'High growth vs equity in income distribution', definition: 'Growth is not automatically shared; without redistribution, growth may worsen inequality.' },
  { term: 'Stakeholders in policy', definition: 'Groups affected by a policy: workers, firms, government, consumers, future generations, the environment.' },
  { term: 'Sustainability (fiscal)', definition: 'Whether government debt is sustainable over time without disruptive adjustment.' },
  { term: 'Sustainability (environmental)', definition: 'Whether economic activity can be maintained without depleting natural capital or damaging ecosystems.' },
];

// Sorted alphabetically for the UI.
export const GLOSSARY_SORTED = [...GLOSSARY].sort((a, b) => a.term.localeCompare(b.term));
