// macrow quizzes — one quiz per module. Each quiz has 6-8 questions of
// mixed format (multiple choice, true/false, short answer). The questions
// are tied to the lessons in the module so a student who just finished
// 3.1 should be able to pass the 3.1 quiz without going elsewhere.
//
// Question types:
//   mc      — multiple choice, options: [{id, text, correct}]
//   tf      — true/false, options: [{id: 'true', text: 'True'}, {id: 'false', text: 'False'}], correct is 'true' or 'false'
//   short   — short answer, accepted: array of acceptable answers (case-insensitive)
//
// The renderer does not grade 'short' questions automatically — it asks the
// student to self-verify against the shown correct answer.

export const QUIZZES = {
  '3.1': {
    moduleId: '3.1',
    title: 'Measuring economic activity',
    blurb: 'Test how well you can define, distinguish, and calculate the basic national income measures.',
    questions: [
      {
        id: '3.1-q1',
        type: 'mc',
        prompt: 'In the circular flow, which of these is an *injection*?',
        options: [
          { id: 'a', text: 'Saving' },
          { id: 'b', text: 'Taxes' },
          { id: 'c', text: 'Imports' },
          { id: 'd', text: 'Investment' },
        ],
        correct: 'd',
        explain: 'Injections are I + G + X. Saving, taxes, and imports are leakages.',
      },
      {
        id: '3.1-q2',
        type: 'tf',
        prompt: 'In equilibrium, injections equal leakages (I + G + X = S + T + M).',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'When the circular flow is at rest, every dollar injected is offset by a dollar leaked out into saving, taxes, or imports.',
      },
      {
        id: '3.1-q3',
        type: 'mc',
        prompt: 'Real GDP is calculated by:',
        options: [
          { id: 'a', text: 'Multiplying nominal GDP by the price deflator' },
          { id: 'b', text: 'Adding net primary income to nominal GDP' },
          { id: 'c', text: 'Dividing nominal GDP by the price deflator and multiplying by 100' },
          { id: 'd', text: 'Subtracting depreciation from nominal GDP' },
        ],
        correct: 'c',
        explain: 'Real GDP = (Nominal GDP / Deflator) × 100, which strips out the effect of price changes.',
      },
      {
        id: '3.1-q4',
        type: 'short',
        prompt: 'What is the formula for GDP per capita?',
        accepted: ['real gdp / population', 'gdp / population', 'real gdp divided by population', 'gdp per person', 'gdp divided by population'],
        explain: 'GDP per capita = Real GDP ÷ Population. It is the standard proxy for average living standards.',
      },
      {
        id: '3.1-q5',
        type: 'mc',
        prompt: 'Which measure adjusts for differences in cost of living across countries?',
        options: [
          { id: 'a', text: 'Nominal GDP' },
          { id: 'b', text: 'Real GDP' },
          { id: 'c', text: 'GDP at PPP' },
          { id: 'd', text: 'GNI per capita' },
        ],
        correct: 'c',
        explain: 'GDP at Purchasing Power Parity (PPP) adjusts for price level differences so a dollar buys the same bundle in every country.',
      },
      {
        id: '3.1-q6',
        type: 'tf',
        prompt: 'HDI is broader than GDP per capita — it also includes life expectancy and education.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'The Human Development Index combines income (GDP per capita), health (life expectancy) and education (mean / expected years of schooling).',
      },
      {
        id: '3.1-q7',
        type: 'mc',
        prompt: 'Which of the following is NOT counted in GDP?',
        options: [
          { id: 'a', text: 'A new car produced this year' },
          { id: 'b', text: 'Government spending on a new bridge' },
          { id: 'c', text: 'Unpaid housework' },
          { id: 'd', text: 'A haircut at a salon' },
        ],
        correct: 'c',
        explain: 'Unpaid household work and other non-market production are not in GDP. Only market transactions (or imputed ones like imputed rent) are counted.',
      },
    ],
  },

  '3.2': {
    moduleId: '3.2',
    title: 'Aggregate demand and aggregate supply',
    blurb: 'AD/AS model mechanics, the three-region SRAS, and what shifts each curve.',
    questions: [
      {
        id: '3.2-q1',
        type: 'mc',
        prompt: 'A decrease in consumer confidence will:',
        options: [
          { id: 'a', text: 'Shift AD right' },
          { id: 'b', text: 'Shift AD left' },
          { id: 'c', text: 'Shift SRAS right' },
          { id: 'd', text: 'Shift LRAS right' },
        ],
        correct: 'b',
        explain: 'Lower consumer confidence reduces consumption, a component of AD, shifting AD left.',
      },
      {
        id: '3.2-q2',
        type: 'tf',
        prompt: 'The short-run aggregate supply curve slopes upward over its middle region.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'The SRAS has three regions: flat at low Y, upward-sloping in the middle, and vertical at Yf.',
      },
      {
        id: '3.2-q3',
        type: 'mc',
        prompt: 'Which of the following would shift SRAS left?',
        options: [
          { id: 'a', text: 'A rise in productivity' },
          { id: 'b', text: 'A fall in the price of oil' },
          { id: 'c', text: 'An increase in wages' },
          { id: 'd', text: 'An increase in consumer spending' },
        ],
        correct: 'c',
        explain: 'Higher input costs (like wages) shift SRAS left. Productivity gains and lower input costs shift it right. AD components do not move SRAS.',
      },
      {
        id: '3.2-q4',
        type: 'short',
        prompt: 'What does the long-run aggregate supply (LRAS) curve represent?',
        accepted: ['potential output', 'potential gdp', 'full employment output', 'y f', 'y_f', 'yf', 'natural rate of unemployment output', 'output at the natural rate of unemployment'],
        explain: 'LRAS is the economy\'s potential output — the level of real GDP consistent with the natural rate of unemployment, given its resources and technology.',
      },
      {
        id: '3.2-q5',
        type: 'mc',
        prompt: 'If AD shifts right while the economy is on the vertical part of SRAS:',
        options: [
          { id: 'a', text: 'Real GDP rises and the price level rises' },
          { id: 'b', text: 'Real GDP is unchanged and the price level rises' },
          { id: 'c', text: 'Real GDP rises and the price level is unchanged' },
          { id: 'd', text: 'Real GDP is unchanged and the price level is unchanged' },
        ],
        correct: 'b',
        explain: 'At full capacity (vertical SRAS), output is pinned at Yf. The rightward AD shift raises the price level only.',
      },
      {
        id: '3.2-q6',
        type: 'tf',
        prompt: 'In the monetarist view, LRAS is vertical at the natural rate of unemployment.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'Monetarists (and new classical economists) treat LRAS as vertical: long-run output is supply-determined and demand-side shocks only move prices.',
      },
      {
        id: '3.2-q7',
        type: 'mc',
        prompt: 'Self-correction after a positive AD shock (above-potential output) is best described as:',
        options: [
          { id: 'a', text: 'SRAS shifts right as wages and other input prices rise' },
          { id: 'b', text: 'SRAS shifts left as wages and other input prices rise' },
          { id: 'c', text: 'AD shifts left as consumer confidence falls automatically' },
          { id: 'd', text: 'LRAS shifts right as capital accumulates' },
        ],
        correct: 'b',
        explain: 'Above potential, tight labour markets push wages up; higher input costs shift SRAS left, returning output to Yf at a higher price level.',
      },
    ],
  },

  '3.3': {
    moduleId: '3.3',
    title: 'Macroeconomic objectives',
    blurb: 'Growth, unemployment, inflation, balance of payments — definitions, measures, and trade-offs.',
    questions: [
      {
        id: '3.3-q1',
        type: 'mc',
        prompt: 'Which of these is the standard ILO definition of unemployment?',
        options: [
          { id: 'a', text: 'People not working but willing to work at the prevailing wage' },
          { id: 'b', text: 'People claiming unemployment benefits' },
          { id: 'c', text: 'Adults not in paid employment' },
          { id: 'd', text: 'People earning less than the median wage' },
        ],
        correct: 'a',
        explain: 'The ILO defines the unemployed as people of working age without work, available to start, and actively seeking employment at the prevailing wage.',
      },
      {
        id: '3.3-q2',
        type: 'mc',
        prompt: 'The natural rate of unemployment includes:',
        options: [
          { id: 'a', text: 'Only frictional unemployment' },
          { id: 'b', text: 'Frictional and structural unemployment, but not cyclical' },
          { id: 'c', text: 'Only cyclical unemployment' },
          { id: 'd', text: 'All forms of unemployment including cyclical' },
        ],
        correct: 'b',
        explain: 'The natural rate comprises frictional (between-job) and structural (skills mismatch) unemployment. Cyclical unemployment is the part that varies with the cycle.',
      },
      {
        id: '3.3-q3',
        type: 'tf',
        prompt: 'Headline CPI inflation includes food and energy; core CPI excludes them.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'Core CPI strips out volatile food and energy prices to reveal the underlying trend.',
      },
      {
        id: '3.3-q4',
        type: 'short',
        prompt: 'What is the formula for the real exchange rate (using CPI)?',
        accepted: ['nominal exchange rate × (foreign cpi / domestic cpi)', 'e × pf / pd', 'e * pf / pd', 'e × p* / p', 'rer = ner × (p*/p)', 'nominal exchange rate * foreign cpi / domestic cpi'],
        explain: 'Real ER = Nominal ER × (Foreign price level / Domestic price level). It captures the price-adjusted value of one currency in terms of another.',
      },
      {
        id: '3.3-q5',
        type: 'mc',
        prompt: 'Stagflation is best described as:',
        options: [
          { id: 'a', text: 'High growth and high inflation' },
          { id: 'b', text: 'Recession and deflation' },
          { id: 'c', text: 'Stagnant output and rising inflation' },
          { id: 'd', text: 'High unemployment and a current account surplus' },
        ],
        correct: 'c',
        explain: 'Stagflation combines stagnant or falling output with rising prices — the 1970s oil-shock pattern.',
      },
      {
        id: '3.3-q6',
        type: 'mc',
        prompt: 'On a Phillips-curve diagram, the long-run Phillips curve (LRPC) is:',
        options: [
          { id: 'a', text: 'Downward-sloping' },
          { id: 'b', text: 'Upward-sloping' },
          { id: 'c', text: 'Vertical at the natural rate of unemployment' },
          { id: 'd', text: 'Horizontal at the expected inflation rate' },
        ],
        correct: 'c',
        explain: 'LRPC is vertical at the natural rate of unemployment — there is no long-run trade-off between inflation and unemployment.',
      },
      {
        id: '3.3-q7',
        type: 'tf',
        prompt: 'The current account of the balance of payments equals the trade balance plus net income and net current transfers.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'CA = trade balance (X − M of goods and services) + net primary income + net secondary (current) transfers.',
      },
    ],
  },

  '3.4': {
    moduleId: '3.4',
    title: 'Inequality and poverty',
    blurb: 'Gini, Lorenz, poverty lines, and the difference between inequality of income and of wealth.',
    questions: [
      {
        id: '3.4-q1',
        type: 'mc',
        prompt: 'The Gini coefficient is measured on a scale from:',
        options: [
          { id: 'a', text: '0 to 1, where 0 is perfect inequality and 1 is perfect equality' },
          { id: 'b', text: '0 to 1, where 0 is perfect equality and 1 is perfect inequality' },
          { id: 'c', text: '0 to 100, where 0 is perfect equality and 100 is perfect inequality' },
          { id: 'd', text: '-1 to +1, where -1 is perfect equality and +1 is perfect inequality' },
        ],
        correct: 'b',
        explain: 'Gini ranges from 0 (perfect equality, the line of equality) to 1 (maximum inequality, one person has everything).',
      },
      {
        id: '3.4-q2',
        type: 'tf',
        prompt: 'The Lorenz curve plots cumulative share of income against cumulative share of population.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'A point (40%, 20%) on the Lorenz curve means the bottom 40% of the population earns 20% of total income.',
      },
      {
        id: '3.4-q3',
        type: 'mc',
        prompt: 'Which of the following is a redistributive policy?',
        options: [
          { id: 'a', text: 'A rise in the central bank policy rate' },
          { id: 'b', text: 'A progressive income tax' },
          { id: 'c', text: 'A depreciation of the currency' },
          { id: 'd', text: 'A cut in tariffs' },
        ],
        correct: 'b',
        explain: 'Progressive taxes take a larger share from high earners, then transfers and public services can redistribute income to lower-income groups.',
      },
      {
        id: '3.4-q4',
        type: 'short',
        prompt: 'Name one common measure of absolute poverty.',
        accepted: ['poverty line', 'international poverty line', 'us$2.15/day', 'us$1.90/day', 'poverty rate', 'basic needs basket', 'multidimensional poverty index', 'mpi', 'relative poverty', 'absolute poverty'],
        explain: 'The World Bank international poverty line is US$2.15/day (2017 PPP). National lines and the Multidimensional Poverty Index are other common measures.',
      },
      {
        id: '3.4-q5',
        type: 'mc',
        prompt: 'A regressive tax:',
        options: [
          { id: 'a', text: 'Takes a larger percentage of income from high earners' },
          { id: 'b', text: 'Takes the same percentage from everyone' },
          { id: 'c', text: 'Takes a larger percentage of income from low earners' },
          { id: 'd', text: 'Is illegal under most constitutions' },
        ],
        correct: 'c',
        explain: 'A regressive tax takes a larger share of income from lower-income groups. Examples: sales taxes / VAT on essentials.',
      },
      {
        id: '3.4-q6',
        type: 'tf',
        prompt: 'Wealth inequality is typically more unequal than income inequality in most countries.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'Wealth accumulates at the top because high earners save and invest a larger share. Net-wealth Ginis are usually 0.7–0.9, much higher than income Ginis (0.25–0.65).',
      },
    ],
  },

  '3.5': {
    moduleId: '3.5',
    title: 'Monetary policy',
    blurb: 'Central banks, money supply, interest rates, and the transmission mechanism.',
    questions: [
      {
        id: '3.5-q1',
        type: 'mc',
        prompt: 'An expansionary monetary policy is best described as:',
        options: [
          { id: 'a', text: 'The central bank raising its policy interest rate' },
          { id: 'b', text: 'The central bank lowering its policy interest rate or buying government bonds' },
          { id: 'c', text: 'The government cutting taxes' },
          { id: 'd', text: 'The government increasing spending' },
        ],
        correct: 'b',
        explain: 'Expansionary monetary policy uses lower rates and/or asset purchases (QE) to lower market interest rates and stimulate AD.',
      },
      {
        id: '3.5-q2',
        type: 'mc',
        prompt: 'In the money market diagram, an increase in the money supply (M_s) will:',
        options: [
          { id: 'a', text: 'Raise the equilibrium interest rate' },
          { id: 'b', text: 'Lower the equilibrium interest rate' },
          { id: 'c', text: 'Raise the equilibrium quantity of money and the interest rate' },
          { id: 'd', text: 'Have no effect on interest rates' },
        ],
        correct: 'b',
        explain: 'A rightward shift of the vertical M_s curve moves the intersection with the downward-sloping money demand curve to a lower interest rate.',
      },
      {
        id: '3.5-q3',
        type: 'tf',
        prompt: 'Quantitative easing (QE) typically expands the central bank\'s balance sheet by buying long-dated government bonds.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'QE raises the price (and lowers the yield) of long-dated bonds while increasing bank reserves at the central bank.',
      },
      {
        id: '3.5-q4',
        type: 'short',
        prompt: 'Name one channel of monetary policy transmission (the path from policy rate to AD).',
        accepted: ['interest rate channel', 'credit channel', 'asset price channel', 'exchange rate channel', 'expectations channel', 'bank lending channel', 'wealth effect channel'],
        explain: 'Common channels: interest rate, credit, asset prices, exchange rate, expectations. The policy rate sets off a chain through these to shift AD.',
      },
      {
        id: '3.5-q5',
        type: 'mc',
        prompt: 'If the central bank raises the policy rate from 3% to 4%, the most likely short-run effect is:',
        options: [
          { id: 'a', text: 'Higher AD, higher output, higher inflation' },
          { id: 'b', text: 'Lower AD, lower output, lower inflation' },
          { id: 'c', text: 'Higher AD, lower output, lower inflation' },
          { id: 'd', text: 'No effect on AD in the short run' },
        ],
        correct: 'b',
        explain: 'Higher rates → lower investment and consumption → lower AD → lower output and lower inflation.',
      },
      {
        id: '3.5-q6',
        type: 'mc',
        prompt: 'Reserve requirements:',
        options: [
          { id: 'a', text: 'Are the fraction of deposits banks must hold as reserves at the central bank' },
          { id: 'b', text: 'Are the same as the policy rate' },
          { id: 'c', text: 'Are set by commercial banks themselves' },
          { id: 'd', text: 'Have no effect on money creation' },
        ],
        correct: 'a',
        explain: 'A reserve requirement is the fraction of deposits banks must keep on reserve, limiting how much they can lend out and create through the money multiplier.',
      },
      {
        id: '3.5-q7',
        type: 'tf',
        prompt: 'Forward guidance is a tool the central bank uses to influence expectations about future policy rates.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'Forward guidance shapes market expectations about the future path of rates, which affects long-term yields and current spending/investment decisions today.',
      },
    ],
  },

  '3.6': {
    moduleId: '3.6',
    title: 'Fiscal policy',
    blurb: 'Government spending, taxation, the multiplier, and the crowding-out debate.',
    questions: [
      {
        id: '3.6-q1',
        type: 'mc',
        prompt: 'Expansionary fiscal policy consists of:',
        options: [
          { id: 'a', text: 'Higher government spending and / or lower taxes' },
          { id: 'b', text: 'Higher interest rates' },
          { id: 'c', text: 'A weaker currency' },
          { id: 'd', text: 'Tighter bank regulation' },
        ],
        correct: 'a',
        explain: 'Expansionary fiscal policy raises G or cuts T. Contractionary policy does the opposite.',
      },
      {
        id: '3.6-q2',
        type: 'mc',
        prompt: 'The simple spending multiplier (1 / (1 − MPC)) equals 5 when the MPC is:',
        options: [
          { id: 'a', text: '0.2' },
          { id: 'b', text: '0.5' },
          { id: 'c', text: '0.8' },
          { id: 'd', text: '0.95' },
        ],
        correct: 'c',
        explain: '1 / (1 − 0.8) = 1 / 0.2 = 5. Higher MPC means more spending stays in the circular flow and gets re-spent.',
      },
      {
        id: '3.6-q3',
        type: 'tf',
        prompt: 'A balanced-budget multiplier of 1 means that an equal increase in G and T raises AD by exactly the size of the G increase.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'A balanced-budget change (ΔG = ΔT) raises AD by ΔG. The tax increase partially offsets the spending increase through the tax multiplier; net effect = ΔG.',
      },
      {
        id: '3.6-q4',
        type: 'short',
        prompt: 'What is "crowding out"?',
        accepted: ['when government borrowing raises interest rates and reduces private investment', 'when higher g reduces i', 'when deficit spending reduces private investment', 'when the government takes resources away from the private sector'],
        explain: 'Crowding out: government borrowing pushes up real interest rates, reducing private investment. The opposite (crowding in) can happen in a recession.',
      },
      {
        id: '3.6-q5',
        type: 'mc',
        prompt: 'The cyclically-adjusted budget balance (CAB) removes the effect of:',
        options: [
          { id: 'a', text: 'Inflation' },
          { id: 'b', text: 'The business cycle' },
          { id: 'c', text: 'Foreign exchange movements' },
          { id: 'd', text: 'Demographic change' },
        ],
        correct: 'b',
        explain: 'CAB strips out the cyclical part of the deficit so we can see the structural balance. A deficit that exists only because the economy is in recession is cyclical, not structural.',
      },
      {
        id: '3.6-q6',
        type: 'mc',
        prompt: 'A regressive tax is one that:',
        options: [
          { id: 'a', text: 'Takes a higher percentage of income from the poor' },
          { id: 'b', text: 'Takes a higher percentage from the rich' },
          { id: 'c', text: 'Charges everyone the same rate' },
          { id: 'd', text: 'Only applies above a threshold income' },
        ],
        correct: 'a',
        explain: 'A regressive tax takes a larger share of income from low earners (e.g. flat-rate sales tax on essentials).',
      },
      {
        id: '3.6-q7',
        type: 'tf',
        prompt: 'A national debt of 100% of GDP is generally considered a high but not necessarily catastrophic level.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'Most economists treat 60% (IMF Article IV) or 100% (commonly cited) as elevated. Sustainability depends on growth, interest rate, and the composition (foreign vs domestic currency) of the debt.',
      },
    ],
  },

  '3.7': {
    moduleId: '3.7',
    title: 'Supply-side policies',
    blurb: 'Market-based and interventionist supply-side policies and the trade-off between them.',
    questions: [
      {
        id: '3.7-q1',
        type: 'mc',
        prompt: 'A market-based supply-side policy is best described as:',
        options: [
          { id: 'a', text: 'Direct government ownership of firms' },
          { id: 'b', text: 'Reducing regulations, taxes, and trade barriers to let markets work' },
          { id: 'c', text: 'Central planning of prices' },
          { id: 'd', text: 'Subsidies to favoured industries' },
        ],
        correct: 'b',
        explain: 'Market-based policies rely on incentives — lower marginal tax rates, deregulation, free trade, flexible labour markets.',
      },
      {
        id: '3.7-q2',
        type: 'mc',
        prompt: 'An interventionist supply-side policy is best described as:',
        options: [
          { id: 'a', text: 'Active government investment in infrastructure, education, training, and industrial strategy' },
          { id: 'b', text: 'Removing all tariffs' },
          { id: 'c', text: 'Cutting the top income tax rate' },
          { id: 'd', text: 'Doing nothing and letting the market self-correct' },
        ],
        correct: 'a',
        explain: 'Interventionist policies target specific market failures: infrastructure, education, R&D, active labour market policies, industrial strategy.',
      },
      {
        id: '3.7-q3',
        type: 'tf',
        prompt: 'A subsidy for vocational training aims to reduce structural unemployment by improving the match between workers\' skills and jobs.',
        options: [{ id: 'true', text: 'True' }, { id: 'false', text: 'False' }],
        correct: 'true',
        explain: 'Active labour market policies (training, apprenticeships) target structural unemployment and frictional unemployment by improving skill-job match.',
      },
      {
        id: '3.7-q4',
        type: 'short',
        prompt: 'Give one criticism of market-based supply-side policies.',
        accepted: ['inequality', 'increases inequality', 'trickle down doesnt work', 'trickle-down', 'ineffective in recession', 'no effect on aggregate demand', 'picking winners', 'regulatory capture', 'externalities not addressed', 'market failures ignored', 'too long to take effect', 'time lag'],
        explain: 'Common criticisms: market-based policies can worsen inequality, may not boost AD in a recession, can ignore externalities, and may not address structural unemployment directly.',
      },
      {
        id: '3.7-q5',
        type: 'mc',
        prompt: 'A "picking winners" criticism of supply-side policy refers to:',
        options: [
          { id: 'a', text: 'Lotteries' },
          { id: 'b', text: 'Government failing to choose which industries to support well' },
          { id: 'c', text: 'Excessive regulation in the financial sector' },
          { id: 'd', text: 'High marginal tax rates' },
        ],
        correct: 'b',
        explain: '"Picking winners" is the critique that governments lack the information to choose which industries will thrive, leading to wasted subsidies and political capture.',
      },
      {
        id: '3.7-q6',
        type: 'mc',
        prompt: 'Investment in public infrastructure (roads, ports, broadband) is best classified as:',
        options: [
          { id: 'a', text: 'A market-based supply-side policy' },
          { id: 'b', text: 'An interventionist supply-side policy' },
          { id: 'c', text: 'A demand-side policy' },
          { id: 'd', text: 'A monetary policy' },
        ],
        correct: 'b',
        explain: 'Public infrastructure is the canonical interventionist supply-side policy — it raises the economy\'s productive capacity by removing bottlenecks.',
      },
    ],
  },
};

export function getQuiz(moduleId) {
  return QUIZZES[moduleId] || null;
}
